## Install Dependencies

In [ ]:
!pip install -q transformers==4.51.3 autoawq "langchain<1.0.0" "langchain-community<1.0.0" langchain-groq \
langchain-huggingface langchain-openai langgraph faiss-cpu flashrank FlagEmbedding \
pypdf sentence-transformers tavily-python markdown deepeval openpyxl langchain-core rank_bm25

## Setup & Authentication

In [1]:
import os
from kaggle_secrets import UserSecretsClient

# disable the buggy Xet protocol and fall back to the standard, stable HTTP download method.
os.environ["HF_HUB_DISABLE_XET"] = "1"

# Securely load the API keys using Kaggle Secrets
user_secrets = UserSecretsClient()
os.environ["GROQ_API_KEY"] = user_secrets.get_secret("GROQ_API_KEY")
# if rate limit hit use this
# os.environ["GROQ_API_KEY"] = user_secrets.get_secret("GROQ_EVAL_API_KEY")
os.environ["HF_TOKEN"] = user_secrets.get_secret("HF_TOKEN")
os.environ["TAVILY_API_KEY"] = user_secrets.get_secret("TAVILY_API_KEY")

print("✅ API Keys loaded successfully.")

✅ API Keys loaded successfully.

## Ingestion & Vector Database

In [2]:
import pickle
import os
from langchain_community.document_loaders import PyPDFDirectoryLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain.retrievers import ParentDocumentRetriever
from langchain.storage import InMemoryStore

# Configuration Paths
DATASET_PATH = "/kaggle/input/datasets/ashishmm10/irdaidataset"
WORKING_INDEX_PATH = "/kaggle/working/faiss_index"
CHUNK_CACHE_PATH = "/kaggle/working/all_chunks.pkl"

# 1. Initialize embeddings
print("Initializing BGE-Large Embeddings...")
embeddings = HuggingFaceEmbeddings(
    model_name="BAAI/bge-large-en-v1.5",
    model_kwargs={'device': 'cuda:1'}
)

FORCE_REBUILD = True  # ⚠️ Set True to rebuild index after chunk changes

# ==========================================
# 2. Always load raw documents
#    ParentDocumentRetriever uses InMemoryStore
#    which is not persisted — must rebuild every session.
# ==========================================
print("🔄 Loading PDFs (always required for ParentDocumentRetriever)...")
if not os.path.exists(DATASET_PATH):
    raise FileNotFoundError(f"PDF directory not found at {DATASET_PATH}.")

loader = PyPDFDirectoryLoader(DATASET_PATH)
documents = loader.load()
print(f"   Loaded {len(documents)} raw PDF pages.")

# ==========================================
# 3. Define splitters
# ==========================================
# Child splitter — small chunks indexed in FAISS for precise retrieval
child_splitter = RecursiveCharacterTextSplitter(
    chunk_size=400,
    chunk_overlap=60,
    separators=["\n\n", "\n", ". ", " "]
)

# Parent splitter — larger chunks returned to the LLM for rich context
parent_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1400,
    chunk_overlap=150,
    separators=["\n\n", "\n", ". ", " "]
)

# ==========================================
# 4. BM25 parent chunks (cached)
# ==========================================
if not FORCE_REBUILD and os.path.exists(CHUNK_CACHE_PATH):
    print("✅ Found cached parent chunks. Loading for BM25...")
    with open(CHUNK_CACHE_PATH, "rb") as f:
        all_chunks = pickle.load(f)
    print(f"   Loaded {len(all_chunks)} parent chunks.")
else:
    print("🔄 Building parent chunks for BM25...")
    all_chunks = parent_splitter.split_documents(documents)

    # Prepend document title to each parent chunk
    # Helps BM25 and embeddings disambiguate across circulars/acts
    for chunk in all_chunks:
        source = chunk.metadata.get("source", "")
        doc_title = os.path.basename(source).replace(".pdf", "").replace("_", " ")
        chunk.page_content = f"[Document: {doc_title}]\n{chunk.page_content}"

    print(f"✅ {len(all_chunks)} parent chunks built and title-prepended.")

    with open(CHUNK_CACHE_PATH, "wb") as f:
        pickle.dump(all_chunks, f)
    print(f"   Cached to {CHUNK_CACHE_PATH}.")

# ==========================================
# 5. FAISS index (cached)
# ==========================================
if not FORCE_REBUILD and os.path.exists(WORKING_INDEX_PATH):
    print(f"✅ Found session FAISS index. Loading...")
    vectorstore = FAISS.load_local(
        WORKING_INDEX_PATH, embeddings, allow_dangerous_deserialization=True
    )
else:
    vectorstore = None

if vectorstore is None:
    print("🔄 Building FAISS index from scratch (this may take a moment)...")
    # FAISS is seeded with parent chunks here so it is consistent with BM25.
    # ParentDocumentRetriever will add child chunks into it next.
    vectorstore = FAISS.from_documents(all_chunks, embeddings)
    vectorstore.save_local(WORKING_INDEX_PATH)
    print(f"✅ FAISS index built and saved to {WORKING_INDEX_PATH}.")

# ==========================================
# 6. ParentDocumentRetriever
#    — child chunks go into FAISS for retrieval
#    — matched child chunks are expanded to parent chunks for LLM context
#    — InMemoryStore is always rebuilt (not persisted)
# ==========================================
print("🔄 Building ParentDocumentRetriever (always rebuilt — InMemoryStore is ephemeral)...")
docstore = InMemoryStore()
parent_retriever = ParentDocumentRetriever(
    vectorstore=vectorstore,
    docstore=docstore,
    child_splitter=child_splitter,
    parent_splitter=parent_splitter,
)
parent_retriever.add_documents(documents)
print(f"✅ ParentDocumentRetriever ready — child chunks in FAISS, parents in docstore.")

Initializing BGE-Large Embeddings...

2026-04-12 05:15:55.599811: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1775970956.092349     148 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1775970956.214775     148 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1775970957.284777     148 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775970957.284811     148 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775970957.284813     148 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1775970957.284816     148 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/52.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/779 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.34G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/366 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/125 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/191 [00:00<?, ?B/s]

🔄 Loading PDFs (always required for ParentDocumentRetriever)...
   Loaded 699 raw PDF pages.
🔄 Building parent chunks for BM25...
✅ 1521 parent chunks built and title-prepended.
   Cached to /kaggle/working/all_chunks.pkl.
🔄 Building FAISS index from scratch (this may take a moment)...
✅ FAISS index built and saved to /kaggle/working/faiss_index.
🔄 Building ParentDocumentRetriever (always rebuilt — InMemoryStore is ephemeral)...
✅ ParentDocumentRetriever ready — child chunks in FAISS, parents in docstore.

## LangGraph Architecture

In [3]:
from typing import TypedDict
from langgraph.graph import StateGraph, END
from langchain_groq import ChatGroq

from langchain.retrievers.contextual_compression import ContextualCompressionRetriever
from langchain_community.cross_encoders import HuggingFaceCrossEncoder
from langchain.retrievers.document_compressors import CrossEncoderReranker
from sentence_transformers import CrossEncoder as RawCrossEncoder
from langchain_community.tools.tavily_search import TavilySearchResults
from langchain_core.messages import SystemMessage, HumanMessage

# ═══════════════════════════════════════════════════════════════════
# 🔴 IMPROVEMENT: BM25 Hybrid Search (keyword + semantic)
# ═══════════════════════════════════════════════════════════════════
from langchain_community.retrievers import BM25Retriever
from langchain.retrievers import EnsembleRetriever

# ==========================================
# 1. Initialize Tools & LLMs
# ==========================================
primary_llm = ChatGroq(model="openai/gpt-oss-120b", temperature=0)

router_llm = ChatGroq(
    model="llama-3.3-70b-versatile", # Now using stronger model for routing decision
    temperature=0,
    max_retries=2
)

# ── Query-aware BM25/FAISS weight selector ──────────────────────
import re as _re

_CLAUSE_PATTERN = _re.compile(
    r"section\s+\d|clause\s+\d|regulation\s+\d|rule\s+\d|schedule\s+\d|"
    r"chapter\s+\d|sub-?\s*section|paragraph\s+\d|article\s+\d",
    _re.IGNORECASE,
)

def get_retriever_weights(query: str) -> tuple[float, float]:
    """Return (bm25_weight, faiss_weight) based on query specificity."""
    if _CLAUSE_PATTERN.search(query):
        print("   ⚖️  Clause-specific query → BM25 0.6 / FAISS 0.4")
        return 0.6, 0.4
    print("   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65")
    return 0.35, 0.65

# BM25 on parent chunks (richer keyword surface for regulatory clauses)
bm25_retriever = BM25Retriever.from_documents(all_chunks, k=22)

# FAISS with MMR — child chunks indexed, parent chunks returned via ParentDocumentRetriever
# Use parent_retriever directly as the semantic leg of the ensemble
parent_retriever.search_kwargs = {"k": 22, "fetch_k": 44, "lambda_mult": 0.75}

# Static ensemble with balanced default weights (overridden per-query in retrieve_and_rerank)
ensemble_retriever = EnsembleRetriever(
    retrievers=[bm25_retriever, parent_retriever],
    weights=[0.35, 0.65]
)

# ── Upgraded reranker: BGE-reranker-large ───────────────────────
_raw_reranker = RawCrossEncoder(
    "BAAI/bge-reranker-large",
    device="cuda:1",
    max_length=512,
)
hf_reranker = HuggingFaceCrossEncoder(
    model_name="BAAI/bge-reranker-large",
    model_kwargs={"device": "cuda:1"},
)
compressor = CrossEncoderReranker(model=hf_reranker, top_n=5)

compression_retriever = ContextualCompressionRetriever(
    base_compressor=compressor,
    base_retriever=ensemble_retriever,
)
print("✅ Hybrid retriever ready: BM25(k=22) + ParentDoc-FAISS(k=22) → BGE-reranker-large(top_n=5)")

# ── Tiered Domain Strategy ───────────────────────────────────────
REGULATORY_DOMAINS = [
    "irdai.gov.in", "pib.gov.in", "finmin.nic.in", "egazette.gov.in",
]

INSURER_DOMAIN_MAP = {
    "care health": "careinsurance.com", "star health": "starhealth.in",
    "niva bupa": "nivabupa.com", "hdfc ergo": "hdfcergo.com",
    "bajaj allianz": "bajajallianz.com", "icici lombard": "icicilombard.com",
    "manipal cigna": "manipalcigna.com", "new india": "newindia.co.in",
    "united india": "uiic.co.in", "national insurance": "nationalinsurance.nic.co.in",
    "aditya birla": "adityabirlacapital.com", "sbi general": "sbigeneral.in",
    "reliance health": "reliancegeneral.co.in", "tata aig": "tataaig.com",
    "max bupa": "nivabupa.com", "sbi life": "sbilife.co.in",
}

INSURER_DISCLOSURE_DOMAINS = [
    "hdfclife.com", "iciciprulife.com", "maxlifeinsurance.com",
    "starhealth.in", "careinsurance.com", "acko.com", "sbilife.co.in",
    "licindia.in", "icicilombard.com", "hdfcergo.com", "nivabupa.com",
    "manipalcigna.com", "newindia.co.in", "orientalinsurance.org.in",
    "uiic.co.in", "nationalinsurance.nic.co.in",
    "lexology.com", "veritaslegal.in",  # Legal analysis sites
]

BLOCKED_DOMAINS = [
    "policybazaar.com", "coverfox.com", "insurancedekho.com",
    "bankbazaar.com", "reddit.com", "quora.com", "medium.com",
]

def build_tavily_search(query: str) -> TavilySearchResults:
    q = query.lower()
    regulatory_terms = [
        "regulation", "circular", "compliance", "compliant", "schedule",
        "master circular", "chapter", "section", "rule", "act",
        "guideline", "direction", "notification", "gazette",
        "irdai", "clause", "obligation"
    ]
    insurer_disclosure_terms = [
        "annual report", "annual-report", "board committee", "board committees",
        "corporate governance", "governance report", "public disclosure",
        "publicly disclosed", "disclosure", "investor relations",
        "committee structure", "how are leading insurers", "how are insurers",
        "leading insurers", "major insurers", "top insurers", "private insurers"
    ]
    current_status_terms = [
        "latest", "current", "as of", "recent", "recently",
        "who is the current", "has been launched", "latest status",
        "rollout status", "appointed", "chairperson", "ceo"
    ]
    named_insurer_domains = [
        domain for name, domain in INSURER_DOMAIN_MAP.items() if name in q
    ]
    is_regulatory = any(term in q for term in regulatory_terms)
    wants_insurer_disclosure = any(term in q for term in insurer_disclosure_terms)
    wants_current_status = any(term in q for term in current_status_terms)

    if named_insurer_domains:
        domains = list(set(named_insurer_domains + REGULATORY_DOMAINS))
        print(f"   🏢 Domain tier: NAMED INSURER + REGULATORY → {domains}")
        return TavilySearchResults(max_results=6, include_domains=domains)

    if is_regulatory and wants_insurer_disclosure:
        domains = list(set(REGULATORY_DOMAINS + INSURER_DISCLOSURE_DOMAINS))
        print(f"   📄 Domain tier: INSURER DISCLOSURE + REGULATORY → {domains}")
        return TavilySearchResults(max_results=8, include_domains=domains)

    if is_regulatory or wants_current_status:
        print(f"   🔒 Domain tier: REGULATORY ONLY → {REGULATORY_DOMAINS}")
        return TavilySearchResults(max_results=5, include_domains=REGULATORY_DOMAINS)

    print("   🌐 Domain tier: OPEN WEB (blocking aggregators)")
    return TavilySearchResults(max_results=6, exclude_domains=BLOCKED_DOMAINS)


# ==========================================
# 2. State Definition
# ==========================================
class AgentState(TypedDict):
    query: str
    chat_history: str
    route: str
    router_raw_output: str
    router_confidence: float
    fallback_used: bool
    fallback_reason: str
    retrieved_docs: list
    web_results: list
    web_context: str
    final_answer: str


# ==========================================
# 3. Nodes
# ==========================================
import re

def detect_route_confidence(raw_text: str) -> tuple[str, float]:
    text = raw_text.strip()
    route_match = re.search(r"ROUTE\s*:\s*(RAG|WEB|BOTH)", text, re.IGNORECASE)
    conf_match = re.search(r"CONFIDENCE\s*:\s*([0-9]*\.?[0-9]+)", text, re.IGNORECASE)
    route = route_match.group(1).upper() if route_match else "BOTH"
    confidence = float(conf_match.group(1)) if conf_match else 0.0
    if route not in {"RAG", "WEB", "BOTH"}:
        route = "BOTH"
    confidence = max(0.0, min(confidence, 1.0))
    return route, confidence


def intent_router(state: AgentState):
    system_prompt = f"""
You are a routing assistant for an IRDAI regulatory QA system.

Choose exactly one route:
- RAG  = answer should come from the local IRDAI corpus only
- WEB  = answer requires fresh/current/public web information
- BOTH = answer genuinely needs both the corpus and live web evidence

Routing rules:
1. Use RAG when the question asks about:
   - sections, clauses, schedules, regulations, circulars, guidelines
   - definitions, duties, timelines, penalties, committee requirements
   - content already contained in IRDAI PDFs or legal corpus

2. Use WEB when the question asks about:
   - current office holders
   - latest launch status or rollout status
   - recent appointments
   - current insurer product wording or current market status
   - any fact that may have changed after the corpus was built
   - WHETHER something has been published, approved, or announced by a regulator
     (e.g. "Has IRDAI published any approved proposals...") — even if a regulation
     name appears in the query, the question is about current publication STATUS

3. Use BOTH only when:
   - the question needs a legal/regulatory baseline from corpus
   - AND also needs current status / latest public update from web
   - e.g. "What are the obligations under X, and are there any recent official
     notifications updating them?" — needs corpus for the base rule, web for updates

Important:
- Do NOT choose BOTH just because you are uncertain.
- BOTH is not a default.
- If unsure between RAG and BOTH, prefer RAG unless the query explicitly needs freshness.
- If unsure between WEB and BOTH, prefer WEB unless the query explicitly asks for regulation/compliance interpretation.

Previous conversation:
{state.get('chat_history', 'None')}

Respond in exactly this format:
ROUTE: <RAG|WEB|BOTH>
CONFIDENCE: <0.00 to 1.00>
REASON: <one short line>
"""
    query = state["query"]
    try:
        response = router_llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=query)
        ])
    except Exception as e:
        print(f"⚠️ Router model failed: {e}, falling back to primary")
        response = primary_llm.invoke([
            SystemMessage(content=system_prompt),
            HumanMessage(content=query)
        ])

    raw_output = response.content
    predicted_route, confidence = detect_route_confidence(raw_output)

    fallback_used = False
    fallback_reason = ""

    # ═══════════════════════════════════════════════════════════════
    # Post-router override: catch current-status and update queries
    # that the LLM misclassifies due to regulatory keywords in query.
    # Patterns are semantic signals, NOT copied from test questions.
    # ═══════════════════════════════════════════════════════════════
    query_lower = state["query"].lower()

    # Queries asking WHETHER a regulator has published/approved something
    # are current-status checks → WEB, even if a regulation name appears
    web_status_signals = [
        "has irdai published", "has irdai approved", "has irdai announced",
        "has irdai released", "who is the current", "latest status",
        "has been launched", "rollout status",
    ]
    # Queries needing corpus baseline + recent regulatory updates → BOTH
    both_upgrade_signals = [
        "any recent official", "any updates to", "recent notifications",
        "recent circulars", "recently updated",
    ]

    if predicted_route == "RAG":
        for signal in web_status_signals:
            if signal in query_lower:
                print(f"   ⚠️ Route override: RAG → WEB (signal: '{signal}')")
                predicted_route = "WEB"
                fallback_used = True
                fallback_reason = f"web_status_override:{signal}"
                break

    if predicted_route == "RAG":
        for signal in both_upgrade_signals:
            if signal in query_lower:
                print(f"   ⚠️ Route upgrade: RAG → BOTH (signal: '{signal}')")
                predicted_route = "BOTH"
                fallback_used = True
                fallback_reason = f"both_upgrade_override:{signal}"
                break

    if confidence < 0.6:
        fallback_used = True
        fallback_reason = f"low_router_confidence:{confidence:.2f}"
        predicted_route = "BOTH"

    return {
        "route": predicted_route,
        "router_raw_output": raw_output,
        "router_confidence": confidence,
        "fallback_used": fallback_used,
        "fallback_reason": fallback_reason,
    }


# ═══════════════════════════════════════════════════════════════════
# Dynamic document index — derived from chunk metadata at runtime.
# Maps human-readable doc name variants to their source basename.
# No hardcoded strings: works automatically for any corpus.
# ═══════════════════════════════════════════════════════════════════
def build_doc_index(chunks: list) -> dict:
    index = {}
    seen = set()
    for chunk in chunks:
        src = chunk.metadata.get("source", "")
        basename = os.path.basename(src).replace(".pdf", "")
        if basename in seen:
            continue
        seen.add(basename)
        readable = basename.replace("_", " ").lower()
        index[readable] = basename
        if readable.startswith("the "):
            index[readable[4:]] = basename  # Also match without leading "the"
    return index

DOC_INDEX = build_doc_index(all_chunks)
print(f"✅ Dynamic doc index built: {len(DOC_INDEX)} name variants across {len(set(DOC_INDEX.values()))} documents")


# ═══════════════════════════════════════════════════════════════════
# 🔴 IMPROVEMENT: Query decomposition for multi-part questions
# ═══════════════════════════════════════════════════════════════════
def decompose_query(query: str) -> list:
    """Break multi-part regulatory questions into focused sub-queries."""
    try:
        response = router_llm.invoke([
            SystemMessage(content="""You are a search query optimizer for regulatory document retrieval.
Break the following question into 2-3 focused sub-queries that will help find the relevant document sections.
Each sub-query should target a SPECIFIC fact or clause.
Output one sub-query per line. No numbering, no bullet points, just the queries."""),
            HumanMessage(content=query)
        ])
        sub_queries = [q.strip() for q in response.content.strip().split("\n") if q.strip()]
        return sub_queries[:3]
    except Exception:
        return []


def retrieve_and_rerank(state: AgentState):
    query = state["query"]
    query_lower = query.lower()

    # ── Strict metadata filter: if query names a specific document,
    #    restrict retrieval to that document's chunks only.
    target_doc = None
    for keyword, basename in DOC_INDEX.items():
        if keyword in query_lower:
            target_doc = basename
            break

    # ── Query-aware weights: re-build ensemble per query ────────
    bm25_w, faiss_w = get_retriever_weights(query)
    if bm25_w != 0.35:  # only rebuild if weights differ from default
        _ensemble = EnsembleRetriever(
            retrievers=[bm25_retriever, parent_retriever],
            weights=[bm25_w, faiss_w],
        )
        _comp_retriever = ContextualCompressionRetriever(
            base_compressor=compressor,
            base_retriever=_ensemble,
        )
    else:
        _comp_retriever = compression_retriever  # reuse default

    # ── Main query: retrieve + rerank against original ──────────
    main_docs = _comp_retriever.invoke(query)
    all_docs = list(main_docs)

    # ── Sub-queries: raw ensemble only (no per-sub reranking) ───
    sub_queries = decompose_query(query)
    print(f"   🔍 Query decomposition: {len(sub_queries)} sub-queries generated")
    for sq in sub_queries:
        try:
            sq_docs = ensemble_retriever.invoke(sq)
            all_docs.extend(sq_docs)
        except Exception:
            pass

    # ── Deduplicate by content fingerprint ──────────────────────
    seen = set()
    unique_docs = []
    for d in all_docs:
        key = d.page_content[:200]
        if key not in seen:
            seen.add(key)
            unique_docs.append(d)

    # ── Strict doc filter (replaces soft boosting) ──────────────
    if target_doc:
        filtered = [d for d in unique_docs
                    if target_doc.lower() in d.metadata.get("source", "").lower()]
        if filtered:
            unique_docs = filtered
            print(f"   📎 Strict doc filter: {len(unique_docs)} chunks from '{target_doc}' only")
        else:
            # Fallback to boost if filter leaves nothing
            non_targeted = [d for d in unique_docs if d not in filtered]
            unique_docs = filtered + non_targeted
            print(f"   📎 Doc filter found 0 results — fallback to full pool")

    # ── Unified final rerank: score all candidates against ORIGINAL query ──
    if len(unique_docs) > 5:
        pairs = [(query, d.page_content) for d in unique_docs]
        scores = _raw_reranker.predict(pairs, show_progress_bar=False)
        ranked = sorted(zip(scores, unique_docs), key=lambda x: x[0], reverse=True)
        unique_docs = [d for _, d in ranked[:5]]
        print(f"   🏆 Unified final rerank: {len(pairs)} candidates → top 5 kept")
    else:
        unique_docs = unique_docs[:5]

    # ── Serialize for state ─────────────────────────────────────
    cleaned_docs = []
    for d in unique_docs:
        cleaned_docs.append({
            "content": d.page_content.strip(),
            "source": d.metadata.get("source", "Unknown"),
            "page": d.metadata.get("page", "Unknown"),
        })

    print(f"   📚 Final context: {len(cleaned_docs)} chunks passed to LLM")
    return {"retrieved_docs": cleaned_docs}

# ==========================================
# grade_and_search (web cache — unchanged)
# ==========================================
import hashlib, json, os

WEB_CACHE_PATH = "/kaggle/working/web_cache.json"

def _load_web_cache() -> dict:
    if os.path.exists(WEB_CACHE_PATH):
        with open(WEB_CACHE_PATH, "r") as f:
            return json.load(f)
    return {}

def _save_web_cache(cache: dict):
    with open(WEB_CACHE_PATH, "w") as f:
        json.dump(cache, f, indent=2)

_web_cache = _load_web_cache()


def grade_and_search(state: AgentState):
    query = state["query"]
    cache_key = hashlib.md5(query.strip().lower().encode()).hexdigest()

    if cache_key in _web_cache:
        cached = _web_cache[cache_key]
        print(f"   📦 Cache hit — using frozen web results ({len(cached['web_results'])} results)")
        return cached

    print(f"\n   [search] Building tiered Tavily search for query...")
    tavily_search = build_tavily_search(query)

    try:
        raw = tavily_search.invoke(query)
        if isinstance(raw, str):
            raw_results = [{"url": "No URL", "content": raw}]
        elif isinstance(raw, list):
            raw_results = []
            for item in raw:
                if isinstance(item, dict):
                    raw_results.append(item)
                elif isinstance(item, str):
                    raw_results.append({"url": "No URL", "content": item})
        else:
            raw_results = []

        filtered_results = []
        for r in raw_results:
            url = r.get("url", "No URL")
            content = r.get("content", "").strip()
            if not content:
                continue
            filtered_results.append({"url": url, "content": content})

        print(f"   ✅ Web search returned {len(filtered_results)} usable results")

        web_context = ""
        for r in filtered_results:
            web_context += f"\n[Source: {r['url']}]\n{r['content']}\n"

        result = {
            "web_results": filtered_results,
            "web_context": web_context.strip(),
        }

    except Exception as e:
        print(f"   ⚠️ Web search failed: {e}")
        result = {"web_results": [], "web_context": ""}

    _web_cache[cache_key] = result
    _save_web_cache(_web_cache)
    print(f"   💾 Web results cached (key: {cache_key[:8]}...)")
    return result


# ═══════════════════════════════════════════════════════════════════
# 🔴 IMPROVEMENT: Simplified, stricter system prompt
# ═══════════════════════════════════════════════════════════════════
def synthesis_and_audit(state: AgentState):
    retrieved_docs = state.get("retrieved_docs", [])
    web_results = state.get("web_results", [])
    query = state["query"]

    # ---- Format RAG context ----
    if isinstance(retrieved_docs, list) and retrieved_docs:
        rag_context_parts = []
        for d in retrieved_docs:
            if isinstance(d, dict):
                content = d.get("content", "").strip()
                source = d.get("source", "Unknown")
                page = d.get("page", "Unknown")
                if content:
                    rag_context_parts.append(f"[Source: {source}, Page: {page}]\n{content}")
            elif isinstance(d, str) and d.strip():
                rag_context_parts.append(d.strip())
        rag_context_text = "\n\n".join(rag_context_parts)
    else:
        rag_context_text = "[NO RAG CONTEXT AVAILABLE]"

    # ---- Format web context ----
    if isinstance(web_results, list) and web_results:
        web_context_parts = []
        for w in web_results:
            if isinstance(w, dict):
                url = w.get("url", "No URL")
                content = w.get("content", "").strip()
                if content:
                    web_context_parts.append(f"[Web: {url}]\n{content}")
        web_context_text = "\n\n".join(web_context_parts)
    else:
        web_context_text = "[NO WEB CONTEXT AVAILABLE]"

    # ── Detect question intent for adaptive output format ───────
    _compliance_signals = [
        "compliant", "non-compliant", "comply", "compliance",
        "violat", "requirement", "obligation", "eligible", "permitted",
        "allowed", "shall", "must", "prohibited", "restrict",
    ]
    _is_compliance_q = any(sig in query.lower() for sig in _compliance_signals)
    _is_web_only = not retrieved_docs or rag_context_text == "[NO RAG CONTEXT AVAILABLE]"

    if _is_compliance_q:
        output_format = """For compliance questions, structure your answer as:
REGULATORY RULE: [Quote or close paraphrase from the source]
CITATION: [Source: document, Page: X]
VERDICT: [COMPLIANT / NON-COMPLIANT / INDETERMINATE]
REASONING: [1–2 sentences connecting rule to the question]"""
    else:
        output_format = """For factual retrieval questions, structure your answer as:
ANSWER: [Direct, precise answer to the question]
CITATION: [Source: document, Page: X — one per factual claim]
NOTES: [Any important caveats or related provisions, if relevant]"""

    web_hardening = ""
    if _is_web_only:
        web_hardening = """
WEB-ONLY RULES (this response uses web context only):
- If a fact is not explicitly confirmed in the retrieved web sources, respond: "No confirmed information found in the retrieved sources for this point."
- Do NOT infer, extrapolate, or fill gaps from general knowledge.
- Limit content from any single web source to 3–4 sentences maximum.
- Prefer official domains (irdai.gov.in, pib.gov.in) over all others.
- If sources conflict, state both positions and cite each.
"""

    system_prompt = f"""You are an IRDAI Regulatory Compliance Analyst. Provide precise, legally-grounded answers using ONLY the evidence provided below.

RESPONSE PROTOCOL:
1. READ all provided context carefully before answering.
2. EXTRACT the specific regulatory rule, clause, or provision that answers the question.
3. CITE every factual claim with [Source: document, Page: X] for RAG or [Web: URL] for web evidence.
4. If the answer is NOT in the provided context, say: "The specific provision is not present in the available documents."

STRICT RULES:
- NEVER state a fact without a citation from the provided context.
- NEVER invent section numbers, clause numbers, committee names, person names, dates, or numerical values.
- NEVER use phrases like "typically", "generally", or "it is common practice" unless directly cited.
- If the query asks for specific numbers (ages, percentages, amounts), either quote the exact number from context or state it is not available.
- Keep the answer focused. Avoid boilerplate sections that don't apply to the question type.
{web_hardening}
OUTPUT FORMAT:
{output_format}

SOURCE PRIORITY:
1. RAG Context (regulatory documents) — primary authority
2. Official IRDAI/government web pages — for current status only
3. Insurer annual reports — for public disclosure questions only
4. Other web sources — only if clearly identified as secondary

RAG Context:
{rag_context_text}

Web Context:
{web_context_text}
"""

    messages = [
        SystemMessage(content=system_prompt),
        HumanMessage(content=query)
    ]

    response = primary_llm.invoke(messages)
    final_text = response.content

    return {"final_answer": final_text}


# ==========================================
# 4. Build Graph (unchanged logic)
# ==========================================
workflow = StateGraph(AgentState)

workflow.add_node("router", intent_router)
workflow.add_node("retrieve", retrieve_and_rerank)
workflow.add_node("search", grade_and_search)
workflow.add_node("synthesize", synthesis_and_audit)

workflow.set_entry_point("router")

def route_workflow(state: AgentState):
    route = state.get("route", "BOTH")
    if route == "RAG":
        return "retrieve"
    elif route == "WEB":
        return "search"
    elif route == "BOTH":
        return "retrieve"
    else:
        return "retrieve"

workflow.add_conditional_edges(
    "router",
    route_workflow,
    {"retrieve": "retrieve", "search": "search"}
)

def after_retrieve_logic(state: AgentState):
    if state.get("route") == "RAG":
        return "synthesize"
    return "search"

workflow.add_conditional_edges(
    "retrieve",
    after_retrieve_logic,
    {"synthesize": "synthesize", "search": "search"}
)

workflow.add_edge("search", "synthesize")
workflow.add_edge("synthesize", END)

app_graph = workflow.compile()
print("✅ Dynamic LangGraph backend compiled and ready.")

config.json:   0%|          | 0.00/801 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.24G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/443 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.1M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/279 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

✅ Hybrid retriever ready: BM25(k=22) + ParentDoc-FAISS(k=22) → BGE-reranker-large(top_n=5)
✅ Dynamic doc index built: 21 name variants across 19 documents
✅ Dynamic LangGraph backend compiled and ready.

**Test Execution**

In [ ]:
# Test the pipeline
test_query = """Under the IRDAI Insurance Fraud Monitoring Framework Guidelines 2025, what are the five official categories of fraud, 
                which committee oversees the framework, and which committee operationalises it?"""

inputs = {
    "query": test_query,
    "chat_history": "",
    "route": "",
    "router_raw_output": "",
    "router_confidence": 0.0,
    "fallback_used": False,
    "fallback_reason": "",
    "retrieved_docs": [],
    "web_results": [],
    "web_context": "",
    "final_answer": ""
}

# ── Quick sanity check before running ──────────────────────────────────────
print("🔍 Domain tier preview for this query:")
_ = build_tavily_search(test_query)  # just prints the tier, doesn't search
print()

print("Initiating Audit...\n")
print("-" * 50)
for output in app_graph.stream(inputs):
    for key, value in output.items():
        print(f"🟢 Node executed: {key}")
print("-" * 50)

print("\n📝 FINAL AUDIT REPORT:\n")
print(value["final_answer"])

**Interactive UI for Q&A (add if needed)**

## **DeepEval Setup**

## Configure DeepEval to use Local Qwen2.5-32B-Instruct-AWQ

In [4]:
# ═══════════════════════════════════════════════════════════════════
# Configure DeepEval — Local Qwen2.5-14B-Instruct-AWQ
# ═══════════════════════════════════════════════════════════════════
# Replaces: Qwen2.5-32B-Instruct-AWQ (timed out on T4×2)
# Why 14B?
#   - Fits on a SINGLE T4 GPU (~8GB AWQ) — no cross-GPU PCIe penalty
#   - 2-3× faster inference vs 32B split across 2 GPUs
#   - Still very capable for structured evaluation JSON tasks
#   - Each metric call: ~10-15s vs ~30-60s with 32B
#   - Total eval time: ~30-60 min vs ~2-3 hours
#
# DEPENDENCY CONSTRAINTS (Kaggle T4 environment):
#   - transformers==4.51.3 (native autoawq, no gptqmodel)
#   - gptqmodel uninstalled (missing C++ kernels on Kaggle)
#   - import awq FIRST to force CPU init, bypass meta tensor crash
# ═══════════════════════════════════════════════════════════════════

import torch
import gc
import awq  # ← MUST import before AutoModelForCausalLM to bypass meta tensor bug
from transformers import AutoModelForCausalLM, AutoTokenizer
from deepeval.models.base_model import DeepEvalBaseLLM

# ── Configuration ─────────────────────────────────────────────────
EVAL_MODEL_ID = "Qwen/Qwen2.5-14B-Instruct-AWQ"

# ── Step 1: Load tokenizer ────────────────────────────────────────
print(f"🔄 Loading tokenizer for {EVAL_MODEL_ID}...")
eval_tokenizer = AutoTokenizer.from_pretrained(
    EVAL_MODEL_ID,
    trust_remote_code=True,
)

# ── Step 2: Load model on a SINGLE GPU ────────────────────────────
# 14B-AWQ (~8GB) fits entirely on one T4 (15GB VRAM)
# device_map="auto" will place everything on cuda:0
# No cross-GPU communication = much faster inference!
print(f"🔄 Loading {EVAL_MODEL_ID} (device_map='auto')...")
print(f"   14B-AWQ fits on a single T4 — no cross-GPU penalty!")

eval_model_raw = AutoModelForCausalLM.from_pretrained(
    EVAL_MODEL_ID,
    torch_dtype=torch.float16,
    device_map="cuda:0",
    trust_remote_code=True,
)

# Show how the model was distributed
if hasattr(eval_model_raw, 'hf_device_map'):
    devices_used = set(str(v) for v in eval_model_raw.hf_device_map.values())
    print(f"✅ Model loaded on device(s): {devices_used}")
else:
    print("✅ Model loaded successfully")

# ── Step 3: Check VRAM usage ──────────────────────────────────────
for i in range(torch.cuda.device_count()):
    allocated = torch.cuda.memory_allocated(i) / 1024**3
    reserved = torch.cuda.memory_reserved(i) / 1024**3
    print(f"   GPU {i}: {allocated:.1f}GB allocated, {reserved:.1f}GB reserved")

# ── Step 4: Define the DeepEval wrapper ───────────────────────────
class LocalQwenEvalLLM(DeepEvalBaseLLM):
    """
    Local Qwen2.5-14B-Instruct-AWQ for DeepEval evaluation.
    No API calls, no Ollama, no rate limits.
    Fits on a single T4 GPU for fast inference.
    """

    def __init__(self, model, tokenizer):
        self._model = model
        self._tokenizer = tokenizer

    def load_model(self):
        return self._model

    def generate(self, prompt: str) -> str:
        messages = [
            {
                "role": "system",
                "content": (
                    "You are a precise evaluation assistant. "
                    "When asked to output JSON, respond with ONLY valid JSON — "
                    "no markdown code fences, no explanatory text, no commentary. "
                    "Just the raw JSON object."
                ),
            },
            {"role": "user", "content": prompt},
        ]

        text = self._tokenizer.apply_chat_template(
            messages, tokenize=False, add_generation_prompt=True
        )
        inputs = self._tokenizer(text, return_tensors="pt").to(
            self._model.device if hasattr(self._model, 'device') else 'cuda:0'
        )

        with torch.no_grad():
            output_ids = self._model.generate(
                **inputs,
                max_new_tokens=1024,   # ← Reduced from 2048; DeepEval only needs short JSON
                temperature=0.1,
                top_p=0.9,
                do_sample=True,
                pad_token_id=self._tokenizer.eos_token_id,
            )

        # Decode only the NEW tokens (skip the input prompt)
        generated_ids = output_ids[0][inputs["input_ids"].shape[1] :]
        result = self._tokenizer.decode(generated_ids, skip_special_tokens=True)
        
        # Clean up any markdown code fences that might wrap JSON
        result = result.strip()
        if result.startswith("```json"):
            result = result[7:]
        if result.startswith("```"):
            result = result[3:]
        if result.endswith("```"):
            result = result[:-3]

        return result.strip()

    async def a_generate(self, prompt: str) -> str:
        return self.generate(prompt)

    def get_model_name(self) -> str:
        return "Qwen2.5-14B-Instruct-AWQ (local, T4)"


# ── Step 5: Instantiate ──────────────────────────────────────────
eval_llm = LocalQwenEvalLLM(
    model=eval_model_raw,
    tokenizer=eval_tokenizer,
)

print(f"\n✅ DeepEval LLM ready: {eval_llm.get_model_name()}")
print(f"   ℹ️  Running locally — ZERO API rate limits!")
print(f"   ℹ️  Single-GPU inference — much faster than 32B split across 2×T4")

/usr/local/lib/python3.12/dist-packages/awq/__init__.py:21: DeprecationWarning:
I have left this message as the final dev message to help you transition.

Important Notice:
- AutoAWQ is officially deprecated and will no longer be maintained.
- The last tested configuration used Torch 2.6.0 and Transformers 4.51.3.
- If future versions of Transformers break AutoAWQ compatibility, please report the issue to the Transformers project.

Alternative:
- AutoAWQ has been adopted by the vLLM Project: https://github.com/vllm-project/llm-compressor

For further inquiries, feel free to reach out:
- X: https://x.com/casper_hansen_
- LinkedIn: https://www.linkedin.com/in/casper-hansen-804005170/

  warnings.warn(_FINAL_DEV_MESSAGE, category=DeprecationWarning, stacklevel=1)
/usr/local/lib/python3.12/dist-packages/torch/jit/_script.py:1480: DeprecationWarning: `torch.jit.script` is deprecated. Please switch to `torch.compile` or `torch.export`.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

🔄 Loading tokenizer for Qwen/Qwen2.5-14B-Instruct-AWQ...

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

🔄 Loading Qwen/Qwen2.5-14B-Instruct-AWQ (device_map='auto')...
   14B-AWQ fits on a single T4 — no cross-GPU penalty!

config.json:   0%|          | 0.00/841 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 3 files:   0%|          | 0/3 [00:00<?, ?it/s]

model-00002-of-00003.safetensors:   0%|          | 0.00/3.97G [00:00<?, ?B/s]

model-00001-of-00003.safetensors:   0%|          | 0.00/3.99G [00:00<?, ?B/s]

model-00003-of-00003.safetensors:   0%|          | 0.00/2.02G [00:00<?, ?B/s]

Sliding Window Attention is enabled but not implemented for `sdpa`; unexpected results may be encountered.

Loading checkpoint shards:   0%|          | 0/3 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/243 [00:00<?, ?B/s]

✅ Model loaded on device(s): {'cuda:0'}
   GPU 0: 9.3GB allocated, 9.3GB reserved
   GPU 1: 5.4GB allocated, 5.5GB reserved

✅ DeepEval LLM ready: Qwen2.5-14B-Instruct-AWQ (local, T4)
   ℹ️  Running locally — ZERO API rate limits!
   ℹ️  Single-GPU inference — much faster than 32B split across 2×T4

## Load the Q&A Dataset from Excel

In [5]:
import warnings
warnings.filterwarnings("ignore", category=DeprecationWarning)

In [6]:
import pandas as pd

EXCEL_PATH = "/kaggle/input/datasets/ashishmm10/qa-dataset/IRDAI_QA_Dataset_v2.xlsx"

qa_df = pd.read_excel(EXCEL_PATH, sheet_name="Dataset")
qa_df.columns = [c.strip().lower() for c in qa_df.columns]

qa_df = qa_df[["q_id", "question", "ground_truth_answer", "expected_route"]].copy()
qa_df.columns = ["q_id", "question", "ground_truth", "route"]

print(f"✅ Loaded {len(qa_df)} Q&A pairs")
print(f"   Route distribution: {qa_df['route'].value_counts().to_dict()}")
display(qa_df[["q_id", "route", "question"]])

✅ Loaded 10 Q&A pairs
   Route distribution: {'RAG': 4, 'WEB': 3, 'BOTH': 3}

  q_id route                                           question
0  Q01   RAG  Under the IRDA Act 1999 Section 5, what is the...
1  Q02   RAG  Under the IRDAI Insurance Fraud Monitoring Fra...
2  Q03   RAG  Under the Master Circular on Corporate Governa...
3  Q04   RAG  Under the Master Circular on Rural, Social Sec...
4  Q05   WEB  As of official IRDAI sources, what is the late...
5  Q06   WEB  Who is the current Chairperson of IRDAI, and w...
6  Q07   WEB  Has IRDAI published any approved Regulatory Sa...
7  Q08  BOTH  Under the IRDAI Bima Sugam Regulations 2024, w...
8  Q09  BOTH  Under the Master Circular on Corporate Governa...
9  Q10  BOTH  Under the Master Circular on Rural, Social Sec...

## Run Pipeline & Collect Results

In [ ]:
# # Run this ONCE if the pipeline fails (need to run this before the pipeline!) 
# print("Pre-fetching and caching web results for all questions...")
# for _, row in qa_df.iterrows():
#     state = {"query": row["question"]}
#     grade_and_search(state)   # populates cache
#     time.sleep(1)             # be polite to Tavily rate limits
# print("✅ Web cache populated. Eval runs will be fully reproducible.")

In [7]:
import time

# Updated!
def run_pipeline(question: str) -> dict:
    inputs = {
        "query": question,
        "chat_history": "",
        "route": "",
        "router_raw_output": "",
        "router_confidence": 0.0,
        "fallback_used": False,
        "fallback_reason": "",
        "retrieved_docs": [],
        "web_results": [],
        "web_context": "",
        "final_answer": "",
    }
    final_state = app_graph.invoke(inputs)
    return final_state

# Updated!
def extract_contexts(state: dict) -> list:
    contexts = []

    rag_docs = state.get("retrieved_docs", [])
    if isinstance(rag_docs, list):
        for doc in rag_docs:
            if isinstance(doc, dict):
                content = doc.get("content", "").strip()
                source = doc.get("source", "Unknown")
                page = doc.get("page", "Unknown")
                if content:
                    contexts.append(f"[Source: {source}, Page: {page}]\n{content}")
            elif isinstance(doc, str) and doc.strip():
                contexts.append(doc.strip())

    web_results = state.get("web_results", [])
    if isinstance(web_results, list):
        for item in web_results:
            if isinstance(item, dict):
                url = item.get("url", "No URL")
                content = item.get("content", "").strip()
                if content:
                    contexts.append(f"[Source: {url}]\n{content}")
            elif isinstance(item, str) and item.strip():
                contexts.append(item.strip())

    return contexts if contexts else ["No context retrieved."]


# ── Run pipeline on all 10 questions ──────────────────────────────────────
# Updated!
results = []

for _, row in qa_df.iterrows():
    q_id = row["q_id"]
    question = row["question"]
    expected_route = row["route"]

    print(f"🔄 Running {q_id} [expected={expected_route}]: {question[:70]}...")
    start = time.time()

    try:
        state = run_pipeline(question)
        answer = state.get("final_answer", "").strip()
        contexts = extract_contexts(state)
        elapsed = round(time.time() - start, 1)

        actual_route = state.get("route", "?")
        fallback_used = state.get("fallback_used", False)
        router_confidence = state.get("router_confidence", 0.0)

        print(
            f"   ✅ {elapsed}s | expected={expected_route} | actual={actual_route} "
            f"| fallback={fallback_used} | conf={router_confidence:.2f} "
            f"| ctx_chunks={len(contexts)} | ans_len={len(answer)} chars"
        )

    except Exception as e:
        print(f"   ❌ Pipeline error: {e}")
        answer = ""
        contexts = ["Pipeline error — no context retrieved."]
        actual_route = "ERROR"
        fallback_used = False
        router_confidence = 0.0
        state = {}

    results.append({
        "q_id": q_id,
        "question": question,
        "ground_truth": row["ground_truth"],
        "answer": answer,
        "contexts": contexts,
        "expected_route": expected_route,
        "actual_route": actual_route,
        "fallback_used": fallback_used,
        "fallback_reason": state.get("fallback_reason", ""),
        "router_confidence": router_confidence,
        "router_raw_output": state.get("router_raw_output", ""),
    })

    time.sleep(15) # ✅ Gives Groq's TPM limit time to cool down

print(f"\n✅ Pipeline completed for all {len(results)} questions.")

🔄 Running Q01 [expected=RAG]: Under the IRDA Act 1999 Section 5, what is the term of office for the ...
   ⚖️  Clause-specific query → BM25 0.6 / FAISS 0.4
   🔍 Query decomposition: 3 sub-queries generated
   📎 Strict doc filter: 14 chunks from 'The_IRDA_Act_1999' only
   🏆 Unified final rerank: 14 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM
   ✅ 5.8s | expected=RAG | actual=RAG | fallback=False | conf=1.00 | ctx_chunks=5 | ans_len=484 chars
🔄 Running Q02 [expected=RAG]: Under the IRDAI Insurance Fraud Monitoring Framework Guidelines 2025, ...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   🏆 Unified final rerank: 35 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM
   ✅ 7.8s | expected=RAG | actual=RAG | fallback=False | conf=0.95 | ctx_chunks=5 | ans_len=1482 chars
🔄 Running Q03 [expected=RAG]: Under the Master Circular on Corporate Governance for Insurers 2024, w...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   📎 Strict doc filter: 40 chunks from 'Master_Circular_on_Corporate_Governance_for_Insurers_2024' only
   🏆 Unified final rerank: 40 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM
   ✅ 8.5s | expected=RAG | actual=RAG | fallback=False | conf=0.95 | ctx_chunks=5 | ans_len=1159 chars
🔄 Running Q04 [expected=RAG]: Under the Master Circular on Rural, Social Sector and Motor Third Part...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   🏆 Unified final rerank: 49 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM
   ✅ 9.9s | expected=RAG | actual=RAG | fallback=False | conf=0.90 | ctx_chunks=5 | ans_len=558 chars
🔄 Running Q05 [expected=WEB]: As of official IRDAI sources, what is the latest publicly visible stat...

   [search] Building tiered Tavily search for query...
   🔒 Domain tier: REGULATORY ONLY → ['irdai.gov.in', 'pib.gov.in', 'finmin.nic.in', 'egazette.gov.in']
   ✅ Web search returned 5 usable results
   💾 Web results cached (key: 57a2b4ce...)
   ✅ 4.6s | expected=WEB | actual=WEB | fallback=False | conf=0.90 | ctx_chunks=5 | ans_len=780 chars
🔄 Running Q06 [expected=WEB]: Who is the current Chairperson of IRDAI, and when were they appointed?...

   [search] Building tiered Tavily search for query...
   🔒 Domain tier: REGULATORY ONLY → ['irdai.gov.in', 'pib.gov.in', 'finmin.nic.in', 'egazette.gov.in']
   ✅ Web search returned 5 usable results
   💾 Web results cached (key: 464f6c93...)
   ✅ 4.6s | expected=WEB | actual=WEB | fallback=False | conf=0.95 | ctx_chunks=5 | ans_len=470 chars
🔄 Running Q07 [expected=WEB]: Has IRDAI published any approved Regulatory Sandbox proposals or cohor...

   [search] Building tiered Tavily search for query...
   🔒 Domain tier: REGULATORY ONLY → ['irdai.gov.in', 'pib.gov.in', 'finmin.nic.in', 'egazette.gov.in']
   ✅ Web search returned 5 usable results
   💾 Web results cached (key: 286d22ee...)
   ✅ 3.1s | expected=WEB | actual=WEB | fallback=False | conf=0.90 | ctx_chunks=5 | ans_len=1063 chars
🔄 Running Q08 [expected=BOTH]: Under the IRDAI Bima Sugam Regulations 2024, what type of company must...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   🏆 Unified final rerank: 63 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM

   [search] Building tiered Tavily search for query...
   🔒 Domain tier: REGULATORY ONLY → ['irdai.gov.in', 'pib.gov.in', 'finmin.nic.in', 'egazette.gov.in']
   ✅ Web search returned 5 usable results
   💾 Web results cached (key: 5c55432f...)
   ✅ 16.2s | expected=BOTH | actual=BOTH | fallback=False | conf=0.90 | ctx_chunks=10 | ans_len=1855 chars
🔄 Running Q09 [expected=BOTH]: Under the Master Circular on Corporate Governance for Insurers 2024, w...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   📎 Strict doc filter: 35 chunks from 'Master_Circular_on_Corporate_Governance_for_Insurers_2024' only
   🏆 Unified final rerank: 35 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM

   [search] Building tiered Tavily search for query...
   📄 Domain tier: INSURER DISCLOSURE + REGULATORY → ['finmin.nic.in', 'nationalinsurance.nic.co.in', 'lexology.com', 'orientalinsurance.org.in', 'icicilombard.com', 'maxlifeinsurance.com', 'uiic.co.in', 'veritaslegal.in', 'iciciprulife.com', 'hdfclife.com', 'nivabupa.com', 'acko.com', 'hdfcergo.com', 'irdai.gov.in', 'starhealth.in', 'pib.gov.in', 'newindia.co.in', 'careinsurance.com', 'licindia.in', 'sbilife.co.in', 'egazette.gov.in', 'manipalcigna.com']
   ✅ Web search returned 8 usable results
   💾 Web results cached (key: c01d24ec...)
   ✅ 11.5s | expected=BOTH | actual=BOTH | fallback=False | conf=0.90 | ctx_chunks=13 | ans_len=1352 chars
🔄 Running Q10 [expected=BOTH]: Under the Master Circular on Rural, Social Sector and Motor Third Part...
   ⚖️  Semantic query → BM25 0.35 / FAISS 0.65
   🔍 Query decomposition: 3 sub-queries generated
   🏆 Unified final rerank: 58 candidates → top 5 kept
   📚 Final context: 5 chunks passed to LLM

   [search] Building tiered Tavily search for query...
   🔒 Domain tier: REGULATORY ONLY → ['irdai.gov.in', 'pib.gov.in', 'finmin.nic.in', 'egazette.gov.in']
   ✅ Web search returned 5 usable results
   💾 Web results cached (key: d416cbae...)
   ✅ 16.2s | expected=BOTH | actual=BOTH | fallback=False | conf=0.90 | ctx_chunks=10 | ans_len=1903 chars

✅ Pipeline completed for all 10 questions.

## Build DeepEval test cases from the results list:

In [8]:
# ═══════════════════════════════════════════════════════════════════
# 🔴 IMPROVEMENT: Route-aware test case builder
#    Tags each test case with its expected route so we can apply
#    the correct metric set during evaluation.
# ═══════════════════════════════════════════════════════════════════
from deepeval.test_case import LLMTestCase

test_cases = []
test_routes = []  # Track expected route for each test case

for r in results:
    tc = LLMTestCase(
        input=r["question"],
        actual_output=r["answer"],
        retrieval_context=r["contexts"],
        expected_output=r["ground_truth"],
    )
    test_cases.append(tc)
    test_routes.append(r["expected_route"])  # "RAG", "WEB", or "BOTH"

print(f"✅ Built {len(test_cases)} DeepEval test cases")
print(f"   Route breakdown: RAG={test_routes.count('RAG')}, WEB={test_routes.count('WEB')}, BOTH={test_routes.count('BOTH')}")

✅ Built 10 DeepEval test cases
   Route breakdown: RAG=4, WEB=3, BOTH=3

## Define metrics:

In [9]:
# ═══════════════════════════════════════════════════════════════════
# 🔴 IMPROVEMENT: Route-aware metrics
#    - RAG / BOTH questions: all 4 metrics
#    - WEB-only questions: only Faithfulness + Answer Relevancy
#      (Contextual Precision/Recall are meaningless when there's no
#       corpus retrieval — they'll always fail for web-only queries)
# ═══════════════════════════════════════════════════════════════════

from deepeval.metrics import (
    FaithfulnessMetric,
    ContextualPrecisionMetric,
    ContextualRecallMetric,
    AnswerRelevancyMetric,
)

# ── Full Metrics (for RAG and BOTH routes) ─────────────────────────
faithfulness_metric = FaithfulnessMetric(
    threshold=0.5,
    model=eval_llm,
    include_reason=True,
    verbose_mode=False,
)

context_precision_metric = ContextualPrecisionMetric(
    threshold=0.5,
    model=eval_llm,
    include_reason=True,
    verbose_mode=False,
)

context_recall_metric = ContextualRecallMetric(
    threshold=0.5,
    model=eval_llm,
    include_reason=True,
    verbose_mode=False,
)

answer_relevancy_metric = AnswerRelevancyMetric(
    threshold=0.5,
    model=eval_llm,
    include_reason=True,
    verbose_mode=False,
)

# ── Two metric sets ────────────────────────────────────────────────
RAG_METRICS = [
    faithfulness_metric,
    context_precision_metric,
    context_recall_metric,
    answer_relevancy_metric,
]

WEB_METRICS = [
    faithfulness_metric,
    answer_relevancy_metric,
]

print(f"✅ RAG/BOTH metrics: {[type(m).__name__ for m in RAG_METRICS]}")
print(f"✅ WEB-only metrics: {[type(m).__name__ for m in WEB_METRICS]}")

✅ RAG/BOTH metrics: ['FaithfulnessMetric', 'ContextualPrecisionMetric', 'ContextualRecallMetric', 'AnswerRelevancyMetric']
✅ WEB-only metrics: ['FaithfulnessMetric', 'AnswerRelevancyMetric']

## Run evaluation in batches with cooldown:

In [10]:
# ══════════════════════════
# Run evaluation in batches 
# ══════════════════════════
import time
import pandas as pd
from deepeval import evaluate as deepeval_evaluate
from deepeval.evaluate.configs import AsyncConfig, DisplayConfig, ErrorConfig

# ── CRITICAL: Set timeouts BEFORE calling evaluate() ─────────────
import os
os.environ["DEEPEVAL_TELEMETRY_OPT_OUT"] = "YES"
os.environ["ERROR_REPORTING"] = "NO"

# DeepEval timeout overrides (default is 180s — too short for local models)
# 14B is ~2-3x faster than 32B, but still slower than API calls
os.environ["DEEPEVAL_PER_TASK_TIMEOUT_SECONDS_OVERRIDE"] = "1200"    # 20 min per test case (all metrics combined)
os.environ["DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE"] = "600"  # 10 min per individual LLM call
os.environ["DEEPEVAL_LOG_STACK_TRACES"] = "1"                        # Full tracebacks if something fails

BATCH_COOLDOWN = 10    # Pause between batches (GPU memory cleanup)
RETRY_COOLDOWN = 30    # Wait before retrying a failed batch
MAX_RETRIES = 2        # Retry failed batches up to 2 times

print("🚀 Starting DeepEval evaluation (Qwen2.5-14B-Instruct-AWQ local, route-aware)...")
print(f"   ⏱️  Per-task timeout: {os.environ['DEEPEVAL_PER_TASK_TIMEOUT_SECONDS_OVERRIDE']}s")
print(f"   ⏱️  Per-attempt timeout: {os.environ['DEEPEVAL_PER_ATTEMPT_TIMEOUT_SECONDS_OVERRIDE']}s")

batch_size = 1
all_results_eval = []

for i in range(0, len(test_cases), batch_size):
    batch = test_cases[i : i + batch_size]
    batch_route = test_routes[i]
    batch_num = i // batch_size + 1

    # Select metrics based on route
    if batch_route == "WEB":
        metrics = WEB_METRICS
        metrics_label = "WEB (Faith+Relevancy only)"
    else:
        metrics = RAG_METRICS
        metrics_label = "RAG/BOTH (all 4 metrics)"

    print(f"\n📦 Evaluating batch {batch_num} (Q{i+1}) [{metrics_label}]...")

    success = False
    for attempt in range(1, MAX_RETRIES + 2):  # +2 because range is exclusive
        try:
            eval_results = deepeval_evaluate(
                test_cases=batch,
                metrics=metrics,
                async_config=AsyncConfig(
                    run_async=False,
                    max_concurrent=1,
                ),
                display_config=DisplayConfig(
                    print_results=True,
                    show_indicator=True,
                ),
                error_config=ErrorConfig(
                    ignore_errors=True,  # Don't crash on JSON parse errors
                ),
            )
            all_results_eval.extend(eval_results.test_results)
            print(f"   ✅ Batch {batch_num} done (attempt {attempt}).")
            success = True
            break

        except Exception as e:
            print(f"   ⚠️  Batch {batch_num} error (attempt {attempt}): {e}")
            if attempt <= MAX_RETRIES:
                print(f"   🔄 Retrying in {RETRY_COOLDOWN}s...")
                time.sleep(RETRY_COOLDOWN)
            else:
                print(f"   ❌ Batch {batch_num} failed after {MAX_RETRIES + 1} attempts. Skipping.")

    # GPU memory cleanup between batches
    if i + batch_size < len(test_cases):
        import torch, gc
        torch.cuda.empty_cache()
        gc.collect()
        print(f"   ⏳ Cooling down {BATCH_COOLDOWN}s (GPU cache cleared)...")
        time.sleep(BATCH_COOLDOWN)

print(f"\n✅ Full DeepEval evaluation complete!")
print(f"   📊 Collected results for {len(all_results_eval)} out of {len(test_cases)} test cases.")

🚀 Starting DeepEval evaluation (Qwen2.5-14B-Instruct-AWQ local, route-aware)...
   ⏱️  Per-task timeout: 1200s
   ⏱️  Per-attempt timeout: 600s

📦 Evaluating batch 1 (Q1) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because there are no contradictions present in the actual output., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all relevant nodes (nodes 1 and 2) provide accurate and pertinent information regarding the term of office and maximum age limits for the Chairperson and whole-time members, while irrelevant nodes (nodes 3, 4, and 5) do not address these specifics and are thus correctly ranked lower., error: None)
  - ✅ Contextual Recall (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all sentences in the expected output align perfectly with the content in the 1st node of the retrieval context., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the response is entirely relevant to the input without any irrelevant statements., error: None)

For test case:

  - input: Under the IRDA Act 1999 Section 5, what is the term of office for the Chairperson and whole-time members, and what are their maximum age limits?
  - actual output: ANSWER: Under Section 5 of the IRDA Act 1999, the Chairperson and each whole‑time member hold office for a term of five years from the date they assume office. A Chairperson cannot continue in office after reaching the age of 65 years, and a whole‑time member cannot continue after reaching the age of 62 years.

CITATION: [Source: The IRDA Act 1999, Page 1]

NOTES: Both the Chairperson and whole‑time members are eligible for reappointment, subject to the respective age limits.
  - expected output: The Chairperson and every other whole-time member shall hold office for a term of five years from the date on which he enters upon his office and shall be eligible for reappointment. No person shall hold office as Chairperson after attaining the age of 65 years. No person shall hold office as a whole-time member after attaining the age of 62 years. A part-time member shall hold office for a term not exceeding five years.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/The_IRDA_Act_1999.pdf, Page: 1]\n[Document: The IRDA Act 1999]\n4. COMPOSITION OF AUTHORITY.--- The Authority shall consist of the following members, namely:-  \n (a) a Chairperson;  \n (b) not more than five whole-time members;  \n (c) not more than four part-time members,  \nto be appo inted by the Central Government from amongst persons of ability, integrity and standing who have \nknowledge or experience in life insurance, general insurance, actuarial science, finance, economics, law, \naccountancy, administration or any other discipline w hich would, in the opinion of the Central Government, be \nuseful to the Authority:  \nProvided that the Central Government shall, while appointing the Chairperson and the whole -time members, \nensure that at least one person each is a person having knowledge or  experience in life insurance, general \ninsurance or actuarial science, respectively.  \n   \n5. TENURE OF OFFICE OF CHAIRPERSON AND OTHER MEMBERS. --(1) The Chairperson and \nevery other whole-time member shall hold office for a term of five years from the date o n which he enters upon \nhis office and shall be eligible for reappointment:  \nProvided that no person shall hold office as a Chairperson after he has attained the age of sixty -five years:  \nProvided further that no person shall hold office as a whole -time member after he has attained the age of sixty -\ntwo years.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/The_IRDA_Act_1999.pdf, Page: 1]\n4. COMPOSITION OF AUTHORITY.--- The Authority shall consist of the following members, namely:-  \n (a) a Chairperson;  \n (b) not more than five whole-time members;  \n (c) not more than four part-time members,  \nto be appo inted by the Central Government from amongst persons of ability, integrity and standing who have \nknowledge or experience in life insurance, general insurance, actuarial science, finance, economics, law, \naccountancy, administration or any other discipline w hich would, in the opinion of the Central Government, be \nuseful to the Authority:  \nProvided that the Central Government shall, while appointing the Chairperson and the whole -time members, \nensure that at least one person each is a person having knowledge or  experience in life insurance, general \ninsurance or actuarial science, respectively.  \n   \n5. TENURE OF OFFICE OF CHAIRPERSON AND OTHER MEMBERS. --(1) The Chairperson and \nevery other whole-time member shall hold office for a term of five years from the date o n which he enters upon \nhis office and shall be eligible for reappointment:  \nProvided that no person shall hold office as a Chairperson after he has attained the age of sixty -five years:  \nProvided further that no person shall hold office as a whole -time member after he has attained the age of sixty -\ntwo years.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/The_IRDA_Act_1999.pdf, Page: 1]\n[Document: The IRDA Act 1999]\ngiven a reasonable opportunity of being heard in the matter.  \n   \n \n7. SALARY AND ALLOWANCES OF CHAIRPERSON AND MEMBERS. --(1) The salary and \nallowances payable to, and other terms and conditions of service of, the members other than part -time members \nshall be such as may be prescribed.  \n(2) The part-time members shall receive such allowances as may be prescribed.  \n(3) The sala ry, allowances and other conditions of service of a member shall not be varied to his \ndisadvantage after appointment.  \n   \n \n8. BAR ON FUTURE EMPLOYMENT OF MEMBERS.-- The Chairperson and the whole -time members \nshall not, for a period of two years from the da te on which they cease to hold office as such, except with the \nprevious approval of the Central Government, accept-  \n (a) any employment either under the Central Government or under any State Government; or  \n (b) any appointment in any company in the insurance sector.  \n   \n \n9. ADMINISTRATIVE POWERS OF CHAIRPERSON.-- The Chairperson shall have the powers of general \nsuperintendence and direction in respect of all administrative matters of the Authority.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/The_IRDA_Act_1999.pdf, Page: 1]\nProvided further that no person shall hold office as a whole -time member after he has attained the age of sixty -\ntwo years.  \n(2) A part-time member shall hold office for a term not exceeding five years from the date on which he \nenters upon his office.  \n(3) Notwithstanding anything contained in sub-section (1) or sub-section (2), a member may -  \n (a) relinquish his office by giving in writing to the Central Government notice of not less than \nthree months; or  \n (b) be removed from his office in accordance with the provisions of section  \n   \n \n6. REMOVAL FROM OFFICE.---(1) The Cen tral Government may remove from office any member \nwho-  \n (a) is, or at any time has been, adjudged as an insolvent; or  \n (b) has become physically or mentally incapable of acting as a member; or  \n (c) has been convicted of any offence which, in the opinion  of the Central Government, involves \nmoral turpitude; or  \n (d) has acquired such financial or other interest as is likely to affect prejudicially his functions as a \nmember; or  \n (e) has so abused his position as to render his continuation in office detrime ntal to the public \ninterest.  \n(2) No such member shall be removed under clause (d) or clause (e) of sub -section (1) unless he has been \ngiven a reasonable opportunity of being heard in the matter.  \n   \n \n7. SALARY AND ALLOWANCES OF CHAIRPERSON AND MEMBERS. --(1) The salary and', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/The_IRDA_Act_1999.pdf, Page: 1]\ngiven a reasonable opportunity of being heard in the matter.  \n   \n \n7. SALARY AND ALLOWANCES OF CHAIRPERSON AND MEMBERS. --(1) The salary and \nallowances payable to, and other terms and conditions of service of, the members other than part -time members \nshall be such as may be prescribed.  \n(2) The part-time members shall receive such allowances as may be prescribed.  \n(3) The sala ry, allowances and other conditions of service of a member shall not be varied to his \ndisadvantage after appointment.  \n   \n \n8. BAR ON FUTURE EMPLOYMENT OF MEMBERS.-- The Chairperson and the whole -time members \nshall not, for a period of two years from the da te on which they cease to hold office as such, except with the \nprevious approval of the Central Government, accept-  \n (a) any employment either under the Central Government or under any State Government; or  \n (b) any appointment in any company in the insurance sector.  \n   \n \n9. ADMINISTRATIVE POWERS OF CHAIRPERSON.-- The Chairperson shall have the powers of general \nsuperintendence and direction in respect of all administrative matters of the Authority.']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=557490;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 587.76s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 1 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 2 (Q2) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 0.7142857142857143, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.71 because the actual output incorrectly states that the Fraud Monitoring Committee (FMC) directly operationalizes the fraud risk management framework and overlooks the role of the Risk Management Committee (RMC) in this process., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all relevant nodes (ranks 1-4) are correctly identified and ranked higher than the irrelevant node (rank 5)., error: None)
  - ✅ Contextual Recall (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the nodes accurately reflect all aspects of the expected output without any discrepancies., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the output perfectly addresses the input without any irrelevant information., error: None)

For test case:

  - input: Under the IRDAI Insurance Fraud Monitoring Framework Guidelines 2025, what are the five official categories of fraud, which committee oversees the framework, and which committee operationalises it?
  - actual output: ANSWER:
- **Five official fraud categories** – Internal Fraud; Distribution Channel Fraud; Policyholder Fraud and/or Claims Fraud; External Fraud; Affinity Fraud or Complex Fraud.
- **Committee that oversees the framework** – the **Risk Management Committee (RMC)** of the insurer.
- **Committee that operationalises the framework** – the **Fraud Monitoring Committee (FMC)** of the insurer.

CITATION:
- Fraud categories: Internal Fraud and Distribution Channel Fraud are listed under 4.1.1 and 4.1.2 [Source: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025, Page: 1]; Policyholder/Claims Fraud, External Fraud and Affinity/Complex Fraud are listed under 4.1.3‑4.1.5 [Source: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025, Page: 2].
- Oversight committee: “The Risk Management Committee (RMC) of the insurer shall be responsible for effective implementation and oversight of the fraud risk management framework.” [Source: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025, Page: 2].
- Operationalising committee: “a Fraud Monitoring Committee (FMC) which shall be responsible for operationalizing the Fraud risk management framework within the insurer…” [Source: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025, Page: 2].

NOTES: The guidelines define the categories and assign specific responsibilities to the RMC (oversight) and FMC (operationalisation) as part of the insurer’s fraud risk management framework.
  - expected output: The five categories are: (1) Internal Fraud involving internal staff including employees and/or senior management, (2) Distribution Channel Fraud involving distribution channels, (3) Policyholder Fraud and/or Claims Fraud involving any person(s) in obtaining coverage or payment, (4) External Fraud involving external parties/service providers/vendors, and (5) Affinity Fraud or Complex Fraud involving collusion among one or more fraud perpetrators. The Risk Management Committee (RMC) is responsible for effective implementation and oversight of the fraud risk management framework. The Fraud Monitoring Committee (FMC) operationalises the framework and reports to the RMC.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Insurance_Fraud_Monitoring_Framework)_Guidelines_2025.pdf, Page: 2]\n[Document: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025]\n3 | P a g e  \n \n4.1.3. Policyholder Fraud and/or Claims Fraud:  Fraud involving any  \nperson(s), in obtaining coverage or payment during the purchase, servicing, \nor claim of an insurance policy. \n4.1.4. External Fraud: Fraud involving external parties’ / service providers / \nvendors etc. \n4.1.5. Affinity Fraud or Complex Fraud: Fraud involving collusion among one \nor more fraud perpetrators in the above categories. \n \n \n5. Fraud Risk Management Framework \n5.1. Every insurer shall target for zero tolerance for fraud  and must put  in place \nappropriate fraud risk management framework sensitive to its business profile to \nenable it to deter, prevent, detect, report and remedy insurance frauds.  \n5.2. The Risk Management Committee  (RMC) of the insurer  shall be responsible for \neffective implementation and oversight of the fraud risk management framework.  \n5.3. The fraud risk management framework shall be specific to the insurer’s business \nconsidering the nature of business, size, risk profile, overall business strategy, \nproducts, distributions channels, technology infrastructure, and any other \napplicable parameter including various activities carried out by the insurer. It shall \ninter-alia include: \n5.3.1. Board approved Anti-Fraud Policy: The Board approved An ti-Fraud \nPolicy shall be relevant to the entire operations of the insurer’s business and', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Insurance_Fraud_Monitoring_Framework)_Guidelines_2025.pdf, Page: 3]\n[Document: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025]\n4 | P a g e  \n \nd) fraud investigation process, including internal turnaround times from \nidentification to remedy, designated officer(s) for reporting incidents \nof fraud and report submission \ne) mechanism for appropriate action in case of non -compliance to the \nfraud risk management framework and against the fraud perpetrators \nf) appropriate and adequate resources to the Fraud Monitoring Unit to \ncarry out its functions effectively. \ng) due diligence procedures for staff recruitment  and vendor \nengagement  \nh) review process to identify "missed" insurance fraud detection \nopportunities \ni) whistle blower protection policy \n \n5.3.2. Fraud Monitoring Committee \n5.3.2.1. Every insurer shall establish: \na) a Fraud Monitoring Committee (FMC) which shall be \nresponsible for operationalizing the Fraud risk management \nframework within the ins urer and oversee activities, as \nappropriate, to ensure fraud deterrence, prevention, detection, \nreporting and remedying.  \nb) a Fraud Monitoring Unit (FMU), independent from internal \naudit, to support FMC in discharging its functions and effective \nimplementation of measures suggested by FMC. \n \n5.3.2.2. Composition of the FMC: The FMC: \na) shall be headed by a KMP and include senior representatives \nfrom relevant departments, such as underwriting, claims, legal \nor any other department as deemed necessary.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Insurance_Fraud_Monitoring_Framework)_Guidelines_2025.pdf, Page: 1]\n[Document: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025]\nfunctions to deter, prevent, detect, report and remedy  frauds; and report such  \nfrauds according to the following categories: \n \n4.1.1. Internal Fraud: Fraud involving internal staff, including employees and \n/ or senior management.  \n4.1.2. Distribution Channel Fraud: Fraud involving distribution channels.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Insurance_Fraud_Monitoring_Framework)_Guidelines_2025.pdf, Page: 1]\n[Document: IRDAI (Insurance Fraud Monitoring Framework) Guidelines 2025]\n2 | P a g e  \n \n\uf0b7 Deliberately misrepresenting /concealing/not disclosing one or more material \nfacts relevant to any decision / transaction, financial or otherwise  \n\uf0b7 Abusing responsibility, position of trust or a fiduciary relationship. \n \n3.2 Red Flag Indicator or RFI means a possible warning sign, that points to a potential \nfraud and may require further investigation or analysis of a fact, event, statement, \nor claim, either alone or with other indicators. \n \n3.3 Cyber or New Age Fraud means any insurance fraud carried out using digital or \nnew age technologies.  \n \n3.4 Distribution Channels shall have the same meaning assigned to it under sub clause \n(8) of clause 5 of IRDAI (Protection of Policyholders’ Interests and Allied Matters \nof Insurers) Regulations, 2024. \n3.5 Words and expressions used and not defined in these guidelines but defined in the \nInsurance Act, 1938 (4 of 1938), Insurance Regulatory and Development Authority \nAct, 1999 (41 of 1999)  shall have the meanings respectively assigned to them in \nthose Acts, Rules, Regulations, Guidelines issued under those Acts, as the case \nmay be. \n \n4. Classification of Frauds \n4.1. Every i nsurer shall establish appropriate systems and processes across its \nfunctions to deter, prevent, detect, report and remedy  frauds; and report such  \nfrauds according to the following categories:', "[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Insurance_Fraud_Monitoring_Framework)_Guidelines_2025.pdf, Page: 0]\n1 | P a g e  \n \n \nRef: IRDAI/IID/GDL/MISC/112/10/2025              Date: 09.10.2025 \n \nInsurance Regulatory and Development Authority of India \n(Insurance Fraud Monitoring Framework) Guidelines, 2025 \n \nIn exercise of power enshrined under Secti on 34 of Insurance Act, 1938 and Section \n14(1) of Insurance Regulatory and Development Authority Act 1999, these Guidelines \nare issued to provide regulatory framework on measures to be taken by Insurers and \nDistribution Channels to address and manage risks emanating from fraud. \n \n1. Short Title, Applicability and Commencement \n1.1. These Guidelines may be called the Insurance Regulatory and Development \nAuthority of India (Insurance Fraud Monitoring Framework) Guidelines, 2025 \n1.2. These guidelines shall be applicable to all insurers and distribution channels \nunless otherwise specified \n1.3. These guidelines shall come into force from 1st April, 2026. \n \n2. Objective \nTo establish a comprehensive framework in order to deter, prevent, detect, report and \nremedy fraud risks effectively across the insurance industry. The se guidelines aim to \nenhance the sector’s resilience against fraud, foster a culture of integrity, protect \npolicyholders' interests, safeguard financial stability and maintain public trust. \n \n3. Definitions \n3.1. “Insurance Fraud” (hereinafter referred to as ‘Fraud’) shall mean an act or"]

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=413000;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 690.9s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 2 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 3 (Q3) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because there are no contradictions present in the actual output., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all relevant nodes (first, second, and third nodes) contain precise and directly related information to the query, while irrelevant nodes (fourth and fifth nodes) clearly state they do not provide specific details, thus maintaining high relevance and ranking accuracy., error: None)
  - ✅ Contextual Recall (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the expected output accurately reflects all relevant information from the retrieval context without any discrepancies., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the output does not contain any irrelevant statements and directly addresses the query regarding the maximum age limits for Non-Executive Directors, tenure rules for Independent Directors, and details about the Managing Director/CEO as per the Master Circular on Corporate Governance for Insurers 2024., error: None)

For test case:

  - input: Under the Master Circular on Corporate Governance for Insurers 2024, what are the maximum age limits for Non-Executive Directors (including Chairperson), Independent Directors' tenure rules, and the Managing Director/CEO?
  - actual output: ANSWER:
- **Non‑Executive Directors (including the Chairperson)** – The maximum age limit is **75 years**; a person may not continue on the board after attaining 75 years. [Source: Master Circular on Corporate Governance for Insurers 2024, Page 5]

- **Independent Directors** – An Independent Director may be appointed for a term of **up to five consecutive years**. He/she may be re‑appointed for a **second term** (i.e., a maximum of **two consecutive terms**) subject to a special resolution. No Independent Director may hold office for more than two consecutive terms, and re‑appointment is permitted only after a **cooling‑off period of at least three years**. [Source: Master Circular on Corporate Governance for Insurers 2024, Page 5]

- **Managing Director / Chief Executive Officer (MD/CEO)** – The same individual cannot hold the MD/CEO (or Whole‑time Director) post for a **continuous period of more than 15 years**. Additionally, **no person shall continue as MD/CEO beyond the age of 70 years** (insurers may set a lower retirement age within this overall limit). [Source: Master Circular on Corporate Governance for Insurers 2024, Page 5]
  - expected output: The maximum age limit for Non-Executive Directors, including the Chairperson of the board, is 75 years. An Independent Director may be appointed for a term of up to five consecutive years and shall be eligible for re-appointment for the second term on passing of a special resolution. No Independent Director shall hold office for more than two consecutive terms, and shall be eligible for re-appointment only after a cooling-off period of at least three years. No person shall continue as Managing Director, CEO or Whole-time Director beyond the age of 70 years, and the same incumbent shall not hold the post for a continuous period of more than 15 years.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 5]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n6 \n \n2.4 Fit and Proper Criteria for Directors \n(a) The maximum age limit for Non -Executive Directors, including the Chairperson of \nthe board, shall be 75 years and after attaining the age of 75 years no person shall \ncontinue on the Board of an insurer.  \nProvided that in cases where the Chairperson/ Non -Executive Director has already \nattained the age of 75 years as on the date of issue of  this circular, such insurers \nshall appoint new incumbent in place of such Chairperson/ Non -Executive Director \nby 30th June, 2024.  \n(b) An Independent Director may be appointed for a term of up to five consecutive \nyears on th e Board of an insurer, and shall be eligible for re -appointment for the \nsecond term on passing of a special resolution by the insurer. No independent \nDirector shall hold office for more than two consecutive terms. Such independent \ndirector shall be eligibl e for re -appointment only after a cooling -off period of at \nleast three years.   \nExplanation: the tenure of the Independent Directors on the board of insurers as on \nthe date of issue of this circular shall be taken into account. If a director has already \ncompleted two consecutive terms on the date of issue of  this circular, such insurers \nshall appoint new incumbent in place of such director(s) by 30th June, 2024. \n(c) Subject to the statutory approvals required from time to time, the post of the', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 5]\n6 \n \n2.4 Fit and Proper Criteria for Directors \n(a) The maximum age limit for Non -Executive Directors, including the Chairperson of \nthe board, shall be 75 years and after attaining the age of 75 years no person shall \ncontinue on the Board of an insurer.  \nProvided that in cases where the Chairperson/ Non -Executive Director has already \nattained the age of 75 years as on the date of issue of  this circular, such insurers \nshall appoint new incumbent in place of such Chairperson/ Non -Executive Director \nby 30th June, 2024.  \n(b) An Independent Director may be appointed for a term of up to five consecutive \nyears on th e Board of an insurer, and shall be eligible for re -appointment for the \nsecond term on passing of a special resolution by the insurer. No independent \nDirector shall hold office for more than two consecutive terms. Such independent \ndirector shall be eligibl e for re -appointment only after a cooling -off period of at \nleast three years.   \nExplanation: the tenure of the Independent Directors on the board of insurers as on \nthe date of issue of this circular shall be taken into account. If a director has already \ncompleted two consecutive terms on the date of issue of  this circular, such insurers \nshall appoint new incumbent in place of such director(s) by 30th June, 2024. \n(c) Subject to the statutory approvals required from time to time, the post of the', "[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 5]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n(c) Subject to the statutory approvals required from time to time, the post of the \nManaging Director (MD), Chief Executive Officer ( CEO) or Whole-time Director \n(WTD) shall not be held by the same incumbent for a continuous period of more \nthan 15 years. Thereafter, the individual shall be eligible for re-appointment as MD, \nCEO or WTD in the same insurer, if considered necessary and desirable by the \nboard, after a cooling off period of at least one year, subject to meeting other \napplicable conditions. No person shall continue as MD , CEO or WTD with an \ninsurer beyond the age of 70 years. Within the overall l imit of 70 years, as part of \ntheir internal policy, individual insurer's Boards are free to specify a lower \nretirement age for the WTDs, including the MD, CEO. \n(d) If the MD , CEO or WTD is appointed by a promoter/ major shareholder, then \nhe/she shall not hold the said posts for a continuous period of more than 12 years. \nHowever, the Authority may, on an application made to it by the concerned insurer \ngiving substantial reasons for the same, permit such MD , CEO or WTDs to hold \noffice up to 15 years.  \n(e) A promoter/shareholder cannot hold a whole time position in the insurer. However, \nthis condition is not applicable in case where an employee becomes a shareholder \nby virtue of shares received through ESOPs /Public Offering during the course of", '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 2]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n3 \n \n(iii) In case of insurer under conglomerate structure and where there is potential \nscope for transfer of risks and conflicts of interests that affect the group \nentities, the optimum composition of Independent  Directors and Non -\nExecutive Directors shall enhance the quality of business judgment and \nbenefits of the shareholders and policyholders.  \n(f) Insurers may have different structures with the Board of Directors headed by an \nexecutive or non -executive Chairperson, with  distinct oversight responsibilities \nover the other Directors and Key Management Persons.  However, to promote \nchecks and balances, it is good practice for the Chair of the Board to be a non -\nexecutive Board member and not serve as chair of any Board committ ee. It is \nexpected that whatever form is taken, the broader elements of good Corporate \nGovernance are present. The proposal for appointment of Chairperson of the Board \nshall be submitted as per Annexure 1 (Form A, B and C) for prior approval of the \nCompetent Authority. Chairperson of the insurer as on the date of issue of this \ncircular is permitted to continue as Chairperson upto 31 st March 2026 or till he/she \ncompletes his/her current tenure, whichever is earlier. In case of insurers, where the \nappointment of Chairperson is governed by the specific', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 0]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\nDate: 22.05.2024 \n \nRef: IRDAI/F&I/CIR/MISC/82/5/2024 \n \nMaster Circular on Corporate Governance for Insurers, 2024 \n1. The Insurance Regulatory and Development Authority of India (Corporate Governance \nfor Insurers) Regulations, 2024  (“the Regula tions”) were notified on 21st March 2024.  \nThe Authority has outlined in general terms, governance responsibiliti es of the Board in \nthe management of insurers under the Regulations. In exercise of the powers conferred by \nSection 34 of the Insurance Act, 193 8, Section 14 of the IRDA Act, 1999 and Regulation \n12 of the Insurance Regulatory and Development Authority of India (Corporate \nGovernance for Insurers) Regulations, 2024 (“the Regulations”) the Authority hereby \nissues this master circular to provide vario us operational and procedural aspects, for \nadoption by all insurers. \n2. The title of this Master Circular shall be “ Master Circular on Corporate Governance for \nInsurers,2024”. \n3. This Master Circular shall be applicable to all insurers except foreign company eng aged \nin re-insurance business through a branch established in India.  \n4. This Master Circular becomes effective upon issuance. However, Insurers are given time \nup to 30 th June, 2024 to ensure compliance with its provisions. Further, where specific \ntimelines a re specified for certain compliances in this Master Circular, such timelines']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=120146;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 691.78s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 3 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 4 (Q4) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because there are no contradictions present in the actual output., error: None)
  - ✅ Contextual Precision (score: 0.75, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.75 because two relevant nodes (first and fourth) provide specific information about the Life Insurers' obligations for Gram Panchayats, while three other nodes (second, third, and fifth) are less relevant as they do not directly address the Life Insurers' obligations for Gram Panchayats., error: None)
  - ✅ Contextual Recall (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the expected output perfectly aligns with the specified nodes in the retrieval context, covering all relevant details without any discrepancies., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the response is entirely relevant to the input without any irrelevant statements., error: None)

For test case:

  - input: Under the Master Circular on Rural, Social Sector and Motor Third Party Obligations 2025, what are the rural-sector obligations for life insurers for FY 2025-26 and FY 2026-27 in terms of Gram Panchayats and percentage of lives to be covered?
  - actual output: **REGULATORY RULE:**
- **FY 2025‑26:** Life insurers must be allotted a minimum of **25,000 Gram Panchayats** and must cover at least **15 % of lives** in each allotted Gram Panchayat.
- **FY 2026‑27:** Life insurers must be allotted a minimum of **50,000 Gram Panchayats**. The coverage percentage is **25 % of lives** for the Gram Panchayats allocated in previous years **and 10 % of lives** for the newly added Gram Panchayats during the year.

**CITATION:** [Source: Master Circular on Rural Social Sector and Motor Third Party Obligations, Page 1]
  - expected output: For life insurers, the collective minimum number of Gram Panchayats to be allotted by the Council is 25,000 in FY 2025-26 and 50,000 in FY 2026-27. The minimum percentage of lives to be covered in a Gram Panchayat is 15% in FY 2025-26. For FY 2026-27, it is 25% for Gram Panchayats allocated for the previous years and 10% for newly added Gram Panchayats during the year.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 1]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nपृ� / Page 11 / 18 \n \n \n \ni. Every life insurer shall cover minimum specified percentage of lives under \nindividual and/ or group insurance policies in allocated Gram Panchayats \nand all insurers collectively shall cover specified minimum number of \nGram panchayats. \nii. The Rural Sector obligation for second and third year, in accordance with \nRegulation 7 (C) of IRDAI (Rural, Social Sector and Motor Third Party \nObligations) Regulations, 2024, shall be as under: -.  \n \nFinancial year Minimum number of Gram \nPanchayats to be allotted \nto the insurers by the \nCouncil \nMinimum percentage of lives \nto be covered in a Gram \npanchayat by the insurers \n2025-26 25000 15% \n2026-27 50000 \n(i) 25% for the GPs allocated \nfor the previous years and \n(ii) 10% for newly added \nGram Panchayats during the \nyear \n \nb) General Insurance (General Insurers other than stand -alone health \ninsurer(SAHI), Agriculture Insurance Co. Ltd (AIC) and ECGC) – \n \ni. Every General Insurer-1 shall cover minimum specified percentage of a) \ndwellings and shops under Fire insurance; and b) vehicles under motor \ninsurance in allocated Gram Panchayats and all insurers collectively shall \ncover specified minimum number of gram panchayats. \nii. The Rural Obligation for second and third year in accordance with \nRegulation 7 ( C) of IRDAI (Rural, Social Sector and Motor Third Party', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 2]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nपृ� / Page 12 / 18 \n \n \nc) Health Insurance (General Insurers including SAHI other than AIC and \nECGC) – \n \ni. Every General Insurer -2 shall cover minimum specified percentage of \nlives under a) health insurance and b) personal accident insurance in \nallocated Gram Panchayats under individual and/ or group insurance \npolicies and all insurers collectively shall cover specified minimum \nnumber of gram panchayats. \nii. The Rural Obligation for second and third year in accordance with \nRegulation 7 (C) of IRDAI (Rural, Social Sector and Motor Third Party \nObligations) Regulations, 2024 shall be as under: - \n \nFinancial \nyear \nMinimum number \nof Gram \nPanchayats to be \nallotted to the \ninsurers by the \nCouncil \nMinimum \npercentage of lives \nto be covered a \nGram panchayat by \nthe insurers under \nHealth insurance  \nMinimum percentage \nof lives to be covered \nin a Gram panchayat \nby the insurers under \npersonal accident \ninsurance \n2025-26 25000 15% 15% \n2026-27 50000 \n(i) 25% for the GPs \nallocated for the \nprevious years and \n(i) 25% for the GPs \nallocated for the \nprevious years and \n(ii) 10% for newly \nadded Gram \nPanchayats during \nthe year \n(ii) 10% for newly \nadded Gram \nPanchayats during \nthe year \n \n(B) Obligations with respect to Social Sector: \n \na) All Insurers –  In accordance with Regulation 7 (C) of IRDAI (Rural, Social', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 2]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nthe year \n \n(B) Obligations with respect to Social Sector: \n \na) All Insurers –  In accordance with Regulation 7 (C) of IRDAI (Rural, Social \nSector and Motor Third Party Obligations) Regulations, 2024, the Social \nSector obligations for the second and third year  in respect of all Insurers \n(Life, General and Standalone Health, excluding AIC and ECGC) shall be as \nunder: \n \nFinancial year Minimum percentage of lives to be covered under \nsocial sector as a proportion of total lives covered \n2025-26 10% \n2026-27 12% \n \n(C) Obligations with respect to Motor Third Party Business: \n \na) All General Insurers (other than stand- alone health insurers, AIC and \nECGC) –  In accordance with Regulation 7 (C) of IRDAI (Rural, Social Sector \nand Motor Third Party Obligations) Regulations, 2024, the obligations with \nrespect to motor third party business for the second and third year in respect', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 1]\nपृ� / Page 11 / 18 \n \n \n \ni. Every life insurer shall cover minimum specified percentage of lives under \nindividual and/ or group insurance policies in allocated Gram Panchayats \nand all insurers collectively shall cover specified minimum number of \nGram panchayats. \nii. The Rural Sector obligation for second and third year, in accordance with \nRegulation 7 (C) of IRDAI (Rural, Social Sector and Motor Third Party \nObligations) Regulations, 2024, shall be as under: -.  \n \nFinancial year Minimum number of Gram \nPanchayats to be allotted \nto the insurers by the \nCouncil \nMinimum percentage of lives \nto be covered in a Gram \npanchayat by the insurers \n2025-26 25000 15% \n2026-27 50000 \n(i) 25% for the GPs allocated \nfor the previous years and \n(ii) 10% for newly added \nGram Panchayats during the \nyear \n \nb) General Insurance (General Insurers other than stand -alone health \ninsurer(SAHI), Agriculture Insurance Co. Ltd (AIC) and ECGC) – \n \ni. Every General Insurer-1 shall cover minimum specified percentage of a) \ndwellings and shops under Fire insurance; and b) vehicles under motor \ninsurance in allocated Gram Panchayats and all insurers collectively shall \ncover specified minimum number of gram panchayats. \nii. The Rural Obligation for second and third year in accordance with \nRegulation 7 ( C) of IRDAI (Rural, Social Sector and Motor Third Party', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 0]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nपृ� / Page 10 / 18 \n \n \nCHAPTER – I \n \nPreliminary \n \n1. Short title and commencement:  \n \na) This master circular is issued under Section 34 of the Insurance Act, 1938, \nSection 14 of the IRDA Act, 1999 and Regulation 9 of the Insurance \nRegulatory and Development Authority of India (Rural, Social Sector and \nMotor Third Party Obligations) Regulations, 2024. This master circular shall \nbe known as Master Circular on Rural, Social Sector and Motor Third Party \nObligations, 2025.  \nb) The master circular is applicable to all life, general and stand- alone health \ninsurers. \nc) Master Circular on Rural, Social Sector and Motor Third Party Obligations, \n2024 shall be applicable for obligations of Insurers for Financial Year (FY) \n2024-25 only. The Master Circular on Rural, Social Sector and Motor Third \nParty Obligations, 2025 shall be applicable for the FY 2025- 26 and F Y \n2026-27. \n \n2. Definitions for the purpose of this Master Circular \n \na) “Regulations” means Insurance Regulatory and Development Authority of \nIndia (Rural, Social Sector and Motor Third Party Obligations) Regulations, \n2024; \nb) “General Insurer – 1” means General Insurers other than Stand Alone \nHealth Insurers (SAHI), Agriculture Insurance Company (AIC) & Export \nCredit Guarantee Corporation of India (ECGC).  \nc) “General Insurer – 2” means General Insurers including Stand Alone Health']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=556940;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 740.05s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 4 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 5 (Q5) [WEB (Faith+Relevancy only)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 0.8, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.80 because the actual output includes a future date that contradicts the provided context., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the output is entirely relevant to the input without any irrelevant statements., error: None)

For test case:

  - input: As of official IRDAI sources, what is the latest publicly visible status of the Bima Sugam Insurance Electronic Marketplace?
  - actual output: ANSWER: The IRDAI has officially notified the “Bima Sugam – Insurance Electronic Marketplace” Regulations, 2024, and the regulation is currently in force. The IRDAI web‑page for the regulation shows it was last updated on 2 April 2026, indicating the framework is publicly active.

CITATION:
- [Source: IRDAI document‑detail page (documentId = 4583640), “Last updated on April 02, 2026”]
- [Source: IRDAI consolidated gazette, “IRDAI (Bima Sugam‑ Insurance Electronic Marketplace) Regulations, 2024, 01‑04‑2024”]

NOTES: The regulation was initially notified on 1 April 2024 and remains the governing framework for the Bima Sugam marketplace as of the latest IRDAI update in April 2026. No subsequent amendment or suspension is indicated in the available official sources.
  - expected output: The answer should reference any official IRDAI press releases or public updates regarding Bima Sugam progress. If no confirmed official launch announcement is found, the answer should explicitly state that the full operational marketplace launch has not been officially confirmed from the sources checked, rather than fabricating a launch date. Any milestones such as the Bima Sugam India Federation website launch or stakeholder discussions should be cited if found.
  - context: None
  - retrieval context: ['[Source: https://irdai.gov.in/document-detail?documentId=4583640]\nआईआरडीएआई (बीमा सुगम – बीमा इलेक्ट्रानिक बाजार स्थान) विनियम, 2024 _ IRDAI (Bima Sugam- Insurance Electronic Marketplace) Regulations, 2024. ... Last updated on April 02, 2026', '[Source: https://irdai.gov.in/consolidated-gazette-notified-regulations]\nIRDAI (Bima Sugam- Insurance Electronic Marketplace) Regulations, 2024, 01-04-2024, IRDAI (Bima Sugam- Insurance Electronic Marketplace) Regulations, 2024, F', '[Source: https://irdai.gov.in/documents/37343/991172/DRAFT+IRDAI+%28Bima+Sugam-IEM%29+Reg.2024-+13.02.2024+-+Annexure-A.pdf/8c66329b-3510-1925-6c56-9ddbab9e53ed?version=1.0&t=1707828164800]\nMarketplace) Regulations 2024 for allowing establishment of a Digital Public. Infrastructure called Bima Sugam - Insurance Electronic Marketplace. This shall', '[Source: https://irdai.gov.in/document-detail?documentId=4414913]\n+ Zoom the page "Zoom the page"). + Link\'s underline "Link\'s underline"). ## Document Detail. #### **एक्सपोजर ड्राफ्ट आईआरडीएआई (बीमा सुगम - बीमा इलेक्ट्रानिक विपणन स्थान) विनियम, 2024 \\_ Exposure Draft IRDAI (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024.pdf**. * एक्सपोजर ड्राफ्ट आईआरडीएआई (बीमा सुगम - बीमा इलेक्ट्रानिक विपणन स्थान) विनियम, 2024 \\_ Exposure Draft IRDAI (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024.pdf. * हिंदी एक्सपोज़र ड्राफ्ट आईआरडीएआई (बीमा सुगम-आईईएम) विनियम 2024 - अनुबंध क \\_ Hindi Exposure Draft IRDAI (Bima Sugam-IEM) Regulation 2024 - Annexure A.pdf. * DRAFT IRDAI (Bima Sugam-IEM) Reg.2024- 13.02.2024 - Annexure-A.pdf. * ड्राफ्ट आईआरडीएआई (बीमा सुगम - बीमा इलेक्ट्रानिक विपणन स्थान) विनियम, 2024 में सुझाव के लिए प्रारूप अनुबंध \'ख\'\\_ Format for Suggestions -IRDAI(Bima Sugam- Insurance Electronic Marketplace)Reg 2024 Annexure-B.pdf.', '[Source: https://irdai.gov.in/documents/37343/365848/Exposure+Draft+IRDAI+%28Bima+Sugam+-+Insurance+Electronic+Marketplace%29+Regulations%2C+2024.pdf/ba1e74bb-f46b-2c1c-c588-4fe8d48c8620?version=1.0&t=1707828509350&ref=thisweekinfintech.com]\nExposure Draft Ref. No: IRDAI/InsurTech/Bimasugam_Regulation/2023-24 13.02.2024 IRDAI (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024 A Digital Public Infrastructure called “Bima Sugam - Insurance Electronic Marketplace” is proposed to be established to empower and protect the interest of policyholders, to increase penetration of insurance in India and to enhance availability, accessibility and affordability. Bima Sugam shall be a one stop solution for all Insurance stakeholder’s vis-a-vis customers, insurers, intermediaries or insurance intermediaries and insurance agents to promote transparency, efficiency, collaboration across the entire insurance value chain, technological innovation in insurance sector, universalize and democratize insurance and to achieve the vision of “Insurance for all by 2047”. Regulatory framework for establishment, governance, functioning of the Bima Sugam - Insurance Electronic Marketplace with following is proposed to be laid down:- a) Not for profit company shall be formed as per Sec 8 of Companies Act, 2013. b) The company shall establish, facilitate, develop, operate and maintain the Marketplace for providing various services to the insurance stakeholders. c) Shareholding of the company widely held amongst life, general and health insurers and no single entity having controlling stake. Shareholders shall contribute to capital as and when required. d) IRDAI would nominate two members on the Board of Company. e) Board to constitute a Risk Management Committee to mitigate various risks. f) Prior approval of Authority for appointment of Chairperson & CEO of the Company. g) Consent based architecture for the services. h) Consumers shall not be charged for availing services of Bima Sugam. The draft Insurance Regulatory and Development Authority of India (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024 is prepared and annexed herewith (Annexure-A). All the stakeholders are requested to forward their comments / suggestions, if any, on the proposed regulations in the attached format (Annexure- B) on or before 5:00 PM on 4th March, 2024 to sageena@ with a copy to keshav@.']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=177716;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 330.3s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 5 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 6 (Q6) [WEB (Faith+Relevancy only)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because there are no contradictions present, indicating perfect alignment between the actual output and the retrieval context., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the output directly addresses the question without any irrelevant statements., error: None)

For test case:

  - input: Who is the current Chairperson of IRDAI, and when were they appointed?
  - actual output: ANSWER: The current Chairperson of the Insurance Regulatory and Development Authority of India (IRDAI) is **Mr. Ajay Seth**, who was appointed on **1 September 2025**.

CITATION: [Web: https://irdai.gov.in/profile-of-top-management — Date: 01-09-2025, Chairperson, Mr. Ajay Seth]

NOTES: Earlier appointments (e.g., Shri Debasish Panda on 11 March 2022) are superseded by the later appointment of Mr. Ajay Seth as reflected in the most recent top‑management profile.
  - expected output: The answer should cite the current IRDAI Chairperson's name and appointment date from an official IRDAI or government source. If the official IRDAI website does not clearly display the current Chairperson, the answer should state that the information could not be confirmed from official sources rather than guessing.
  - context: None
  - retrieval context: ['[Source: https://irdai.gov.in/chairman-whole_time_member_notification]\nChairman & Whole Time Member Notification ; Non-Archived, Appointment notification of Shri Debasish Panda as ChairPerson,IRDAI, 11-03-2022', '[Source: https://irdai.gov.in/profile-of-top-management]\nDate, Title, Short Description. 01-09-2025, Chairperson, Mr. Ajay Seth. 05-01-2021, Member(A) Profile, -. 24-05-2024, Member(D) Profile.', '[Source: https://irdai.gov.in/en/mr-debasish-panda]\nShri Debasish Panda is an officer of Indian Administrative Service of 1987 batch of Uttar Pradesh cadre. His home State is Odisha. He joined as Chairman,', '[Source: https://irdai.gov.in/chairman-and-members-of-authority]\nteam. Mr. Ajay Seth Chairman · Whole Time Member · Part Time Member · Quick Links · E Services & Important Links · IRDAI Head Office · IRDAI Regional Offices.', '[Source: https://irdai.gov.in/document-detail?documentId=386985]\nHe is eligible for re-appointment. The applicant should have a minimum 2 years of residual service as on date of vacancy i.e. not in excess of 63 years of age']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=912717;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 264.16s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 6 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 7 (Q7) [WEB (Faith+Relevancy only)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because there are no contradictions present in the actual output., error: None)
  - ❌ Answer Relevancy (score: 0.3333333333333333, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.33 because there are no specific irrelevant statements mentioned, suggesting the response may lack direct relevance to the query but does not contain clear misinformation or unrelated content., error: None)

For test case:

  - input: Has IRDAI published any approved Regulatory Sandbox proposals or cohorts under the IRDAI Regulatory Sandbox Regulations 2025, and if so, what innovations have been permitted?
  - actual output: REGULATORY RULE: The available IRDAI web documents include the “IRDAI (Regulatory Sandbox) Regulations, 2025” PDF and related exposure‑draft listings, but none of the provided sources contain a list of approved sandbox proposals, cohorts, or the specific innovations that have been permitted under those regulations.

CITATION: [Web: https://irdai.gov.in/search?p_p_id=com_irdai_custom_search_results_CustomSearchResultsPortlet_INSTANCE_QtdSmUnYs3ko&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&q=file+and+use&delta=60&resetCur=false&cur=14] – shows the regulatory sandbox regulation document but does not provide details of approved proposals; no other linked document in the provided context enumerates sandbox cohorts or permitted innovations.

VERDICT: INDETERMINATE

REASONING: Because the supplied web sources do not disclose any approved regulatory‑sandbox proposals or cohorts, nor describe the innovations allowed, a definitive answer cannot be given from the available documents. The specific provision is not present in the available documents.
  - expected output: The answer should check official IRDAI circular/notification pages for any published Regulatory Sandbox approvals or cohort announcements under the 2025 Regulations. If no specific approved proposals are found on official sources, the answer should explicitly state that no approved sandbox proposals could be confirmed from the sources checked, and note that the regulations provide the framework for applications but specific approvals would be published separately.
  - context: None
  - retrieval context: ['[Source: https://irdai.gov.in/search?p_p_id=com_irdai_custom_search_results_CustomSearchResultsPortlet_INSTANCE_QtdSmUnYs3ko&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&q=file+and+use&delta=60&resetCur=false&cur=14]\n| 24-09-2021  101N084V03\\_2015-16.pdf  PDF  725 KB pdf |\n| 22-01-2018  In the matter of M\\_s Happy Insurance TPA Services Pvt Ltd.pdf  PDF  3.6 MB pdf |\n| 22-08-2019  आईआरडीआई (विनियामक सैंडबॉक्स) विनियम, 2019 \\_ IRDAI (Regulatory Sandbox) Regulations, 2019.pdf  PDF  562 KB pdf |\n| 10-06-2022  Press Release - Insurance product approvals made easy.pdf  PDF  65 KB pdf |\n| 25-10-2016  Formats for publishing financial results as required by the SEBI.pdf  PDF  12.2 MB pdf |\n| 24-09-2021  117N097V01\\_2016-17.pdf  PDF  549 KB pdf |\n| 20-05-2019  Preparation of Solvency Statement for FY 2019-20 and Onwards.pdf  PDF  1.6 MB pdf |\n| 17-08-2018  Guidelines on Insurance claims of the victims of recent floods (August 2018.pdf  PDF  94 KB pdf | [...] | 07-12-2017  Constitution of a Working Group to examine ‘Innovations in insurance.pdf  PDF  737 KB pdf |\n| 14-07-2000  IRDA(Assets,Liabilities and Solvency Margins of Insurers)Regulations,2000.pdf  PDF  1.1 MB pdf |\n| 29-08-2000  (Conditions of Service of Officers and Other Employees) Regulations, 2000.pdf  PDF  3 MB pdf |\n| 03-12-2021  Jan swasthaya Beema Yojana\\_2013-2014.pdf  PDF  180 KB pdf |\n| 04-01-2018  Annual report 2016-17.pdf  PDF  4.9 MB pdf |\n| 03-12-2021  Accident Trauma Care Insurance Policy (Group)\\_2013-2014.pdf  PDF  6.4 MB pdf |\n| 08-09-2017  Vigilance Manual 2017.pdf  PDF  4.4 MB pdf |\n| 09-12-2021  sahara order annex 2 copy.pdf  PDF  672 KB pdf |\n| 24-09-2021  101N084V03\\_2015-16.pdf  PDF  725 KB pdf | [...] PDF\n\nAnnual report 2016-17.pdf\n\nPDF\n\nAccident Trauma Care Insurance Policy (Group)\\_2013-2014.pdf\n\nPDF\n\nVigilance Manual 2017.pdf\n\nPDF\n\nsahara order annex 2 copy.pdf\n\nPDF\n\n101N084V03\\_2015-16.pdf\n\nPDF\n\nIn the matter of M\\_s Happy Insurance TPA Services Pvt Ltd.pdf\n\nPDF\n\nआईआरडीआई (विनियामक सैंडबॉक्स) विनियम, 2019 \\_ IRDAI (Regulatory Sandbox) Regulations, 2019.pdf\n\nPDF\n\nPress Release - Insurance product approvals made easy.pdf\n\nPDF\n\nFormats for publishing financial results as required by the SEBI.pdf\n\nPDF\n\n117N097V01\\_2016-17.pdf\n\nPDF\n\nPreparation of Solvency Statement for FY 2019-20 and Onwards.pdf\n\nPDF\n\nGuidelines on Insurance claims of the victims of recent floods (August 2018.pdf\n\nPDF\n\n78\\_Personal Extended Protection Policy wording\\_GEN574.pdf\n\nPDF\n\n101N005V05\\_2017-18.pdf\n\nPDF', '[Source: https://irdai.gov.in/document-detail?documentId=6541188]\n# Navigation\n\nIRDAI\nIRDAI\nMain Content\nText to Audio\nResume\n\nResume/Play\nChange Language\nArrow\nAccessbility Options\nArrow\nZoom the page\nIncrease Text\nDecrease Text\nGrey scale\nHigh Contrast\nLow contrast\nLight background\nLink\'s underline\nReadable font\nReset\n\n## Document Detail\n\nShare\nWhatsapp\nFacebook\nTwitter\nLinkedIn\nEmail\n\nBack "Back")\n\n#### आईआरडीएआई (विनियामक सैंडबाक्स) विनियम, 2024 \\_ IRDAI (Regulatory Sandbox) Regulations, 2025.pdf\n\nDownload\n\nfile icon\n\nआईआरडीएआई (विनियामक सैंडबाक्स) विनियम, 2024 \\_ IRDAI (Regulatory Sandbox) Regulations, 2025.pdf\n\nPrevious\n\nNext\n\nIRDAI logo\n\nWebsite Owned and belongs to Insurance Regulatory and Development Authority of India (IRDAI)', '[Source: https://irdai.gov.in/exposure-drafts?p_p_id=com_irdai_document_media_IRDAIDocumentMediaPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_irdai_document_media_IRDAIDocumentMediaPortlet_filterEntities=HEALTH_INSURERS&_com_irdai_document_media_IRDAIDocumentMediaPortlet_resetCur=false&_com_irdai_document_media_IRDAIDocumentMediaPortlet_delta=40]\n|  | Non-Archived | EXPOSURE DRAFT INSURANCE REGULATORY AND DEVELOPMENT AUTHORITY OF INDIA (REGULATORY SANDBOX) (AMENDMENT) REGULATIONS, 2022 | 03-08-2022 | EXPOSURE DRAFT INSURANCE REGULATORY AND DEVELOPMENT AUTHORITY OF INDIA (REGULATORY SANDBOX) (AMENDMENT) REGULATIONS, 2022 |  | pdf  Exposure Draft- Sandbox Regulation Amendment 2022.pdf 282 KB  Download |\n|  | Non-Archived | Exposure Draft -Other Forms of Capital | 02-08-2022 | Exposure Draft -Other Forms of Capital |  | pdf  Exposure Draft -Other Forms of Capital.pdf 469 KB  Download | [...] |  | Non-Archived | बुनियादी संरचना विशेष प्रयोजन माध्यमों (एसपीवीएस) में बीमाकर्ताओं के निवेश के संबंध में परामर्श / Consultation on Insurers’ Investment in Infrastructure SPVs | 18-12-2025 | बुनियादी संरचना विशेष प्रयोजन माध्यमों (एसपीवीएस) में बीमाकर्ताओं के निवेश के संबंध में परामर्श / Consultation on Insurers’ Investment in Infrastructure SPVs | IRDAI/INV/CIR/08/2024-25/01 | pdf  बुनियादी संरचना विशेष प्रयोजन माध्यमों (एसपीवीएस) में बीमाकर्ताओं के निवेश के संबंध में परामर्श \\_ Consultation on Insurers’ Investment in Infrastructure SPVs.pdf 305 KB  Download | [...] |  | Non-Archived | Proposed Amendments to IRDAI (Third Party Administrators – Health Services) Regulations, 2016 | 15-02-2022 | Proposed Amendments to IRDAI (Third Party Administrators – Health Services) Regulations, 2016 |  | pdf  Proposed Amendments to IRDAI (Third Party Administrators – Health Services) Regulations.pdf 557 KB  Download |', '[Source: https://irdai.gov.in/insurers]\nCouncil for Insurance Ombudsmen\n       Related Organizations\n           Institute of Actuaries of India\n           Insurance Brokers Association of India\n           Indian Institute of Insurance Surveyors & Loss Assessors\n           Insurance Information Bureau of India\n\n       Inter-operable Regulatory Sandbox FAQs\n\n   Media\n       Press Releases\n       Public Notices\n       Response Corner\n       IRDAI Journal\n       International Affairs\n           IRDAI initiative to least developed countries\n           SAIRM\n\n       Media Gallery\n       Events\n           Conferences\n           Seminars\n\n       Speeches\n       Register for Email-Alerts\n       Open House at IRDAI [...] 26-12-2025\n\nNew\n\n##### Image 51: xlsआदित्य बिड़ला सन लाइफ इंश्योरेंस कंपनी लिमिटेड / Aditya Birla Sun Life Insurance Co LtdImage 52: Download0.04 MB\n\nLife Product - Aditya Birla Sun Life Insurance Co. Ltd.\n\n26-12-2025\n\nNew\n\n##### Image 53: xlsइंडिया फर्स्ट लाइफ इंश्योरेंस कं. लिमिटेड / India First Life Insurance Company LtdImage 54: Download0.02 MB\n\nLife Product - India First Life Insurance Company Ltd.\n\n26-12-2025\n\nNew\n\n##### Image 55: xlsएक्को लाइफ इंश्योरेंस लिमिटेड / Acko Life Insurance LtdImage 56: Download0.01 MB\n\nLife Products - Acko Life Insurance Ltd\n\n26-12-2025\n\nNew\n\n##### Image 57: xlsएक्साइड लाइफ / Exide LifeImage 58: Download0.02 MB\n\nLife Products - Exide Life\n\n26-12-2025\n\nNew [...] Life Products - Exide Life\n\n26-12-2025\n\nNew\n\n##### Image 59: xlsएचडीएफसी लाइफ इंश्योरेंस कंपनी लिमिटेड / HDFC Life Insurance Co LtdImage 60: Download0.05 MB\n\nLife Product - HDFC Life Insurance Co. Ltd\n\n26-12-2025\n\nNew\n\n##### Image 61: xlsएजेस फेडरल लाइफ इंश्योरेंस कंपनी लिमिटेड / AGEAS Federal Life Insurance Company LtdImage 62: Download0.02 MB\n\nLife Product - AGEAS Federal Life Insurance Co. Ltd.\n\n26-12-2025\n\nNew\n\n##### Image 63: xlsएडलवाइस टोकियो लाइफ इंश्योरेंस कंपनी लिमिटेड / Edelweiss Tokio Life Insurance Company LimitedImage 64: Download0.02 MB\n\nLife Product - Edelweiss Tokio Life Insurance Company Limited\n\n26-12-2025\n\nNew\n\n##### Image 65: xlsएसबीआई लाइफ इंश्योरेंस कंपनी लिमिटेड / SBI Life Insurance Co LtdImage 66: Download0.03 MB\n\nLife Product - SBI Life Insurance Co Ltd', '[Source: https://irdai.gov.in/corporate-agency1]\npdf\nDownload\n\n18-05-2016\n  \n  \nNew\n\n##### pdf URNs Created before 01st April 2016 in respect of Specified Persons of Download 2.75 MB\n\npdf\nDownload\n\n16-02-2016\n  \n  \nNew\n\n##### pdf Clarifications on IRDAI (Registration of Corporate Agents) Regulations, 201 Download Regulations, 201") 1.16 MB\n\npdf\nDownload\n\n09-03-2026\n  \n  \nNew\n\n##### pdf प्राधिकरण की 134वीं बैठक / 134th Meeting of the Authority Download 0.18 MB\n\npdf\nDownload\n\n13-03-2025\n  \n  \nNew\n\n##### pdf प्रेस विज्ञप्ति प्राधिकरण की 129वीं बैठक / Press Release 129th Authority Meeting Download 0.23 MB\n\npdf\nDownload\n\n04-11-2020\n  \n  \nNew\n\n##### pdf Allowing IC-38 exams for individual agents through remote proctor on pilot Download 0.33 MB\n\npdf\nDownload\n\n08-04-2020\n  \n  \nNew [...] ## What’s New\n\n09-03-2026\n  \n  \nNew\n\n##### pdf प्राधिकरण की 134वीं बैठक / 134th Meeting of the Authority Download 0.18 MB\n\npdf\nDownload\n\n13-03-2025\n  \n  \nNew\n\n##### pdf प्रेस विज्ञप्ति प्राधिकरण की 129वीं बैठक / Press Release 129th Authority Meeting Download 0.23 MB\n\npdf\nDownload\n\n22-12-2021\n  \n  \nNew\n\n##### pdf Final order in the matter of Angel Financial Advisors Pvt Ltd ,Corporate Agents.pdf Download 3.92 MB\n\npdf\nDownload\n\n08-07-2021\n  \n  \nNew\n\n##### pdf LIST OF CORPORATE AGENTS REGISTERED WITH THE AUTHORITY, Jul 2021 Download 0.23 MB\n\npdf\nDownload\n\n04-01-2021\n  \n  \nNew\n\n##### pdf Link to Corporate Agents Login Request, Jan 2021 Attachment-1 Download 0.1 MB\n\npdf\nDownload\n\n04-01-2021\n  \n  \nNew\n\n##### pdf Link to Corporate Agents Login Request, Jan 2021 Download 0.1 MB\n\npdf\nDownload [...] # Navigation\n\nIRDAI\nIRDAI\nMain Content\nText to Audio\nResume\n\nResume/Play\nChange Language\nArrow\nAccessbility Options\nArrow\nZoom the page\nIncrease Text\nDecrease Text\nGrey scale\nHigh Contrast\nLow contrast\nLight background\nLink\'s underline\nReadable font\nReset\n\n## Corporate Agency\n\nback Back;)\n\nback\n\nAccounts\n\nActuarial\n\nAdministration\n\nAgency Distribution\n\nCommunication\n\nPolicyholder protection grievance redressal\n\nCorporate Agency\n\nBoard secretariat\n\nEnforcement\n\nFinance & Accounts\n\nHealth\n\nHR\n\nInspection\n\nIntermediaries\n\nInsurance Marketing Firm\n\nInvestment\n\nIT\n\nLegal\n\nLife\n\nNon-Life\n\nOLI\n\nReinsurance\n\nSectoral Development\n\nSurveyors\n\nVigilance\n\n#### Corporate Agency\n\nNo Image\nShare\nWhatsapp\nFacebook\nTwitter\nLinkedIn\nEmail\n\n## What’s New\n\n09-03-2026\n  \n  \nNew']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Answer Relevancy: 0.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=258133;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 395.97s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 0.0% | Passed: 0 | Failed: 1

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 7 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 8 (Q8) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 0.6, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.60 because the actual output contradicts the retrieval context by incorrectly stating the main objective of Bima Sugam and misrepresenting the reasons for issuing the regulations., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all relevant nodes are ranked higher than the irrelevant ones, ensuring accurate and useful information is prioritized., error: None)
  - ✅ Contextual Recall (score: 0.6666666666666666, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.67 because the output accurately reflects the establishment and objectives of Bima Sugam Insurance Electronic Marketplace as described in the retrieval context, but lacks specific details about the web portion and IRDAI updates., error: None)
  - ✅ Answer Relevancy (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the output does not contain any irrelevant statements. The response is entirely relevant to the input, addressing the regulations, company type, objectives, and the latest progress update on Bima Sugam from IRDAI public sources., error: None)

For test case:

  - input: Under the IRDAI Bima Sugam Regulations 2024, what type of company must establish the Marketplace and what are its main objectives, and what is the latest official progress update on Bima Sugam from IRDAI public sources?
  - actual output: **REGULATORY RULE**
- *Company type*: “Bima Sugam – Insurance Electronic Marketplace shall be established by a **not‑for‑profit company formed under section 8 of the Companies Act, 2013**.”
- *Main objective of the Company*: “The main objective of the Company shall be **to establish, facilitate, develop, operate and maintain the Marketplace for providing various services to the insurance stakeholders**.”
- *Regulatory objectives of the Marketplace*: “The Authority, with the objectives to **empower and protect the interest of policyholders, increase penetration of insurance in India and enhance accessibility**, issues the Regulations to allow establishment of a Digital Public Infrastructure called Bima Sugam … to **promote transparency, efficiency, collaboration across the entire insurance value chain, technological innovation in the insurance sector, universalise and democratise insurance and to achieve the vision of ‘Insurance for all by 2047’**.”

**CITATION**
- [Source: IRDAI (Bima Sugam Insurance Electronic Marketplace) Regulations 2024, Page 1] – company type and main objective.
- [Source: IRDAI (Bima Sugam Insurance Electronic Marketplace) Regulations 2024, Page 0] – regulatory objectives and vision.

**LATEST OFFICIAL PROGRESS UPDATE (IRDAI PUBLIC SOURCE)**
- IRDAI has issued a recent press release titled **“Industry Stakeholders’ Discussion on ‘Public Insurance Registry’ and ‘Bima Sugam’”**, which was approved **16 days ago** (as shown on the IRDAI press‑release portal). This indicates that the Authority is actively engaging stakeholders and moving forward with the implementation of Bima Sugam.

**CITATION**
- [Web: https://irdai.gov.in/press-releases?filtersApplied=true&filterDepartment=NLF] – latest press‑release entry showing the stakeholder discussion and the “16 Days Ago” approval timestamp.
  - expected output: Per the Regulations, Bima Sugam Insurance Electronic Marketplace shall be established by a not-for-profit company formed under section 8 of the Companies Act, 2013. The main objective is to establish a Digital Public Infrastructure as a one-stop solution for all insurance stakeholders (consumers, insurers, intermediaries, agents) to promote transparency, efficiency, collaboration, technological innovation, and universalize insurance to achieve the vision of 'Insurance for all by 2047'. For the web portion, the answer should cite any official IRDAI press releases or updates on Bima Sugam launch progress, and if no confirmed full operational launch is found, it should explicitly say so.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Bima_Sugam_Insurance_Electronic_Marketplace)_Regulations_2024.pdf, Page: 1]\n[Document: IRDAI (Bima Sugam Insurance Electronic Marketplace) Regulations 2024]\nof I938) or the Insurance Regulatory and Development Authority Act, 1999 (41 of 1999) or the Rules or the \nRegulations notified there under shall have the meanings respectively assigned to them in those Acts or the \nRules or the Regulations as the case may be. \nCHAPTER II \nESTABLISHMENT, SHAREHOLDING AND GOVERNANCE OF THE COMPANY \n4. Establishment and Shareholding: \na) Bima Sugam - Insurance Electronic Marketplace shall be established by a not for profit company formed \nunder section 8 of the Companies Act, 2013. \nProvided that no other person shall commence or operate with same or similar objectives of the Marketplace \nand functions of the Company. \nb) The main objective of the Company shall be to establish, facilitate, develop, operate and maintain the \nMarketplace for providing various services to the insurance stakeholders. \nc) The Company after incorporation shall file the Memorandum of Association and Articles of Association with \nthe Authority. Any amendment to the Memorandum of Association of the Company shall be undertaken only \nwith the prior approval of the Competent Authority. \nd) The shareholding of the Company shall be widely held amongst Life Insurers, General Insurers and Health \nInsurers with no single entity having controlling stake. The Company shall transmit, issue any new shares or', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Bima_Sugam_Insurance_Electronic_Marketplace)_Regulations_2024.pdf, Page: 0]\n[Document: IRDAI (Bima Sugam Insurance Electronic Marketplace) Regulations 2024]\nMarketplace) Regulations 2024 for allowing establishment of a Digital Public Infrastructure called Bima \nSugam - Insurance Electronic Marketplace. This shall be a one stop solution for all I nsurance stakeholders \nsuch as consumers, insurers, intermediaries or insurance intermediaries  and insurance agents  to promote \ntransparency, efficiency, collaboration across the entire insurance value chain, technological innovation in \ninsurance sector, universalize and democratize insurance and to achieve the vision of “ Insurance for all by \n2047”. These Regulations specify the regulatory framework for establishment, governance and functioning \nof the Bima Sugam - Insurance Electronic Marketplace, the Company formed for this purpose and for matters \nconnected therewith and incidental thereto. \nb) Broad principles have been laid down in these Regulations to enable the functioning of the Company and the \nBima Sugam - Insurance Electronic Marketplace. The Competent Aut hority may issue guidelines and \ncirculars as the case may be under these Regulations considering the need for effective functioning of the \nMarketplace. \n3. Definitions: \n1. In these Regulations, unless the context otherwise requires: \na) “Act” means the Insurance Act, 1938 (4 of 1938); \nb) “Authority” means the Insurance Regulatory and Development Authority of India established under sub-', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Bima_Sugam_Insurance_Electronic_Marketplace)_Regulations_2024.pdf, Page: 0]\nMarketplace) Regulations 2024 for allowing establishment of a Digital Public Infrastructure called Bima \nSugam - Insurance Electronic Marketplace. This shall be a one stop solution for all I nsurance stakeholders \nsuch as consumers, insurers, intermediaries or insurance intermediaries  and insurance agents  to promote \ntransparency, efficiency, collaboration across the entire insurance value chain, technological innovation in \ninsurance sector, universalize and democratize insurance and to achieve the vision of “ Insurance for all by \n2047”. These Regulations specify the regulatory framework for establishment, governance and functioning \nof the Bima Sugam - Insurance Electronic Marketplace, the Company formed for this purpose and for matters \nconnected therewith and incidental thereto. \nb) Broad principles have been laid down in these Regulations to enable the functioning of the Company and the \nBima Sugam - Insurance Electronic Marketplace. The Competent Aut hority may issue guidelines and \ncirculars as the case may be under these Regulations considering the need for effective functioning of the \nMarketplace. \n3. Definitions: \n1. In these Regulations, unless the context otherwise requires: \na) “Act” means the Insurance Act, 1938 (4 of 1938); \nb) “Authority” means the Insurance Regulatory and Development Authority of India established under sub-', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Bima_Sugam_Insurance_Electronic_Marketplace)_Regulations_2024.pdf, Page: 0]\n[Document: IRDAI (Bima Sugam Insurance Electronic Marketplace) Regulations 2024]\nINSURANCE REGULATORY AND DEVELOPMENT AUTHORITY OF INDIA \nNOTIFICATION \nHyderabad, the 20th March, 2024 \nInsurance Regulatory and Development Authority of India (Bima Sugam - Insurance Electronic \nMarketplace) Regulations, 2024 \nF. No. IRDAI/Reg/5/199/2024. —In exercise o f the powers conferred by clause (zd) of sub section (2) of \nsection 114A of the Insurance Act, 1938, and clause (e) of sub-section 2 of section 14 and clause (e) of sub -section 2 \nof section 26 of the Insurance Regulatory and Development Authority Act, 1999 , the Authority, in consultation with \nthe Insurance Advisory Committee, hereby issues the following Regulations, namely: - \n \n \nCHAPTER I \nPRELIMINARY \n1. Short title and commencement: \na) These Regulations may be called the Insurance Regulatory and Development Authority of India (Bima Sugam \n- Insurance Electronic Marketplace) Regulations, 2024. \nb) These Regulations shall come into force from the date of their publication in the official gazette. \n2. Objectives: \na) The Authority with the objectives to empower and protect the interest of policyholders, to increase penetration \nof insurance in India and to enhance accessibility, issues the IRDAI (Bima Sugam - Insurance Electronic \nMarketplace) Regulations 2024 for allowing establishment of a Digital Public Infrastructure called Bima', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/IRDAI_(Bima_Sugam_Insurance_Electronic_Marketplace)_Regulations_2024.pdf, Page: 0]\nINSURANCE REGULATORY AND DEVELOPMENT AUTHORITY OF INDIA \nNOTIFICATION \nHyderabad, the 20th March, 2024 \nInsurance Regulatory and Development Authority of India (Bima Sugam - Insurance Electronic \nMarketplace) Regulations, 2024 \nF. No. IRDAI/Reg/5/199/2024. —In exercise o f the powers conferred by clause (zd) of sub section (2) of \nsection 114A of the Insurance Act, 1938, and clause (e) of sub-section 2 of section 14 and clause (e) of sub -section 2 \nof section 26 of the Insurance Regulatory and Development Authority Act, 1999 , the Authority, in consultation with \nthe Insurance Advisory Committee, hereby issues the following Regulations, namely: - \n \n \nCHAPTER I \nPRELIMINARY \n1. Short title and commencement: \na) These Regulations may be called the Insurance Regulatory and Development Authority of India (Bima Sugam \n- Insurance Electronic Marketplace) Regulations, 2024. \nb) These Regulations shall come into force from the date of their publication in the official gazette. \n2. Objectives: \na) The Authority with the objectives to empower and protect the interest of policyholders, to increase penetration \nof insurance in India and to enhance accessibility, issues the IRDAI (Bima Sugam - Insurance Electronic \nMarketplace) Regulations 2024 for allowing establishment of a Digital Public Infrastructure called Bima', '[Source: https://irdai.gov.in/documents/37343/365848/Exposure+Draft+IRDAI+%28Bima+Sugam+-+Insurance+Electronic+Marketplace%29+Regulations%2C+2024.pdf/ba1e74bb-f46b-2c1c-c588-4fe8d48c8620?version=1.0&t=1707828509350&ref=thisweekinfintech.com]\nExposure Draft Ref. No: IRDAI/InsurTech/Bimasugam_Regulation/2023-24 13.02.2024 IRDAI (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024 A Digital Public Infrastructure called “Bima Sugam - Insurance Electronic Marketplace” is proposed to be established to empower and protect the interest of policyholders, to increase penetration of insurance in India and to enhance availability, accessibility and affordability. Bima Sugam shall be a one stop solution for all Insurance stakeholder’s vis-a-vis customers, insurers, intermediaries or insurance intermediaries and insurance agents to promote transparency, efficiency, collaboration across the entire insurance value chain, technological innovation in insurance sector, universalize and democratize insurance and to achieve the vision of “Insurance for all by 2047”. Regulatory framework for establishment, governance, functioning of the Bima Sugam - Insurance Electronic Marketplace with following is proposed to be laid down:- a) Not for profit company shall be formed as per Sec 8 of Companies Act, 2013. b) The company shall establish, facilitate, develop, operate and maintain the Marketplace for providing various services to the insurance stakeholders. c) Shareholding of the company widely held amongst life, general and health insurers and no single entity having controlling stake. Shareholders shall contribute to capital as and when required. d) IRDAI would nominate two members on the Board of Company. e) Board to constitute a Risk Management Committee to mitigate various risks. f) Prior approval of Authority for appointment of Chairperson & CEO of the Company. g) Consent based architecture for the services. h) Consumers shall not be charged for availing services of Bima Sugam. The draft Insurance Regulatory and Development Authority of India (Bima Sugam - Insurance Electronic Marketplace) Regulations, 2024 is prepared and annexed herewith (Annexure-A). All the stakeholders are requested to forward their comments / suggestions, if any, on the proposed regulations in the attached format (Annexure- B) on or before 5:00 PM on 4th March, 2024 to sageena@ with a copy to keshav@.', '[Source: https://irdai.gov.in/documents/37343/991172/DRAFT+IRDAI+%28Bima+Sugam-IEM%29+Reg.2024-+13.02.2024+-+Annexure-A.pdf/8c66329b-3510-1925-6c56-9ddbab9e53ed?version=1.0&t=1707828164800]\na) Bima Sugam - Insurance Electronic Marketplace shall be a not for profit entity established through a Company formed under section 8 of the Companies. Act,', '[Source: https://noc.irdai.gov.in/FAQs]\nIRDAI (Bima Sugam- Insurance Electronic Marketplace) Regulations, 2024. Provides regulatory framework around Bima Sugam. https://irdai.gov.in/document-detail', "[Source: https://irdai.gov.in/press-releases?filtersApplied=true&filterDepartment=NLF]\nLast Updated · Sub Title · Reference No · Documents. Non-Archived, Press release on ... Public Insurance Registry' and 'Bima Sugam', 232 KB, Approved, 16 Days Ago.", "[Source: https://irdai.gov.in/press-releases]\nLast Updated ... 'सार्वजनिक बीमा रजिस्ट्री' और 'बीमा सुगम' विषय पर उद्योग के हितधारकों की चर्चा / Industry Stakeholders' Discussion on 'Public Insurance Registry' and 'Bima Sugam'"]

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=200589;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 890.85s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 8 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 9 (Q9) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 0.75, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.75 because the actual output incorrectly suggests that the Audit Committee is the sole board committee that insurers must establish, despite this detail not being specified in the retrieval context., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because the single relevant node (first node) provides detailed information about the mandatory Audit Committee, which is crucial for answering the question. All subsequent nodes are less relevant as they do not fully address the query regarding all mandatory board committees and their structures., error: None)
  - ✅ Contextual Recall (score: 0.5, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.50 because while the first sentence aligns with the content of the 1st node in the retrieval context, the second sentence's specifics about disclosure methods are not directly mentioned, leading to a moderate match., error: None)
  - ✅ Answer Relevancy (score: 0.5, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.50 because the response did not provide specific information about how leading insurers structure their board committees, which was part of the original question., error: None)

For test case:

  - input: Under the Master Circular on Corporate Governance for Insurers 2024, what are the mandatory board committees that every insurer must constitute, and how are leading insurers publicly structuring these committees in their recent disclosures?
  - actual output: **REGULATORY RULE:**
The Master Circular on Corporate Governance for Insurers, 2024 requires every insurer to constitute an **Audit Committee** as a mandatory board committee.  The circular states: “Every Insurer shall constitute an Audit Committee as per Section 177 of the Companies Act… (a) … the Audit Committee (mandatory)”【Source: Master Circular on Corporate Governance for Insurers 2024, Page 8】.

**CITATION:**
[Source: Master Circular on Corporate Governance for Insurers 2024, Page 8]

**VERDICT:**
COMPLIANT (with respect to the requirement to have a mandatory Audit Committee)

**REASONING:**
The circular explicitly lists the Audit Committee as the only board committee that insurers must establish.  It does not prescribe any other mandatory committees; other committees such as the Nomination & Remuneration Committee, CSR Committee, and With‑Profits Committee are mentioned as non‑mandatory.

**Public disclosures of leading insurers:**
The specific ways in which leading insurers are publicly structuring their board committees in recent disclosures are **not provided in the available documents**.  No excerpts or citations from insurer annual reports or other disclosures are present in the supplied context.

**CITATION FOR INDETERMINATE PART:**
“The specific provision is not present in the available documents.”
  - expected output: The Master Circular requires every insurer to constitute the following mandatory committees: (1) Audit Committee as per Section 177 of the Companies Act comprising minimum three directors with majority being Independent Directors, (2) Investment Committee, (3) Risk Management Committee, (4) Policyholder Protection and Grievance Redressal Committee, and (5) Nomination and Remuneration Committee. For the web portion, the answer should describe how leading insurers publicly disclose their committee structures in annual reports or corporate governance sections, citing only what is found on official insurer websites. If insufficient insurer-specific disclosures are found, the answer should state this explicitly.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 8]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n(f) Reporting to the Board \nThe general roles and responsibilities of the Committees are as detailed below. \n4.1 Audit Committee (mandatory) \n(a) Every Insurer shall constitute an Audit Committee as per Section 177 of the \nCompanies Act, as amended from time to time, including in relation to its \ncomposition. Currently, as required under Section 177 of the Companies Act, 2013, \nthe Audit Committee shall comprise minimum of three directors, majority of whom \nshall be Independent Directors. The Chair of the Board should not be a member of \nthe Audit Committee. \n(b) The Audit Committee shall oversee the financial statements, financial reporting, \nstatement of cash flow and disclosure processes both on an annual and quarterly \nbasis. It shall set -up procedures and processes to address all concerns relating to \nadequacy of checks and control mechanisms. \n(c) The Chairperson of the Audit Committee should be an Independent Director of the \nBoard with  an accounting/finance/audit experience and may be a Chartered', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 8]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n9 \n \ndisclosure requirements of this master circular; and all such transactions may be grouped \ntogether under the related party transactions. \n3.6 Related Party transactions should be approved and conducted in a manner that ensures \nproper management of conflict of interest and protection of the interest of the company and \nits policyholders. \n4. Delegation of Functions - Committees of the Board: \nWith a view to providing adequate Board time for discharge of the significant corporate \nresponsibilities, the Board can consider setting up of various Committees of Directors by \ndelegating the overall monitoring responsibilities af ter laying down the roles and \nresponsibilities of these Committees to the Board. However, it is emphasized that the \noverall responsibility for directing the affairs of the insurers shall be with the Board and it \nshall continue to exercise its oversight directly on matters that are not specifically delegated \nto any of its Committees. \nThe following aspects need to be defined in respect of the role and functions of the \nCommittees: \n(a) Constitution \n(b) Objectives \n(c) Responsibilities \n(d) Frequency of meeting / quorum requirements \n(e) Appointment and removal of members \n(f) Reporting to the Board \nThe general roles and responsibilities of the Committees are as detailed below. \n4.1 Audit Committee (mandatory)', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 18]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\n19 \n \n(D) Approving compliance programmes, reviewing their effectiveness \non a regular basis and signing off on any material compliance \nissues or matters. \n(E) Ensuring that the board approved Code of Conduct is followed, \nexpectations of operational transparency to stakeholde rs are met \nand at the same time maintaining confidentiality of information to \nfoster a culture of good decision-making \n4.9 Meetings, Appointment/ Removal of Members and Quorum  \n(a) The mandatory Committees, except Nomination and Remuneration Committee, the \nCorporate Social Responsibility Committee  and the With -Profits Committee shall \nmeet at least four times in a year and not more than four months shall elapse \nbetween two successive meetings of such Committees. \n(b) The quorum shall be two members or one -third of the me mbers of the Committee, \nwhichever is greater . In case of , independent director(s) is/ are mandated to be in \nany of the Committees, at least one such independent director or his alternate \ndirector, should necessarily be present to form the quorum.  However, where the \nIndependent Director is mandated to chair the committee, the meeting cannot be \nconducted in his absence.  \n(c) The conditions specified in Section 161(2) of the Companies Act  shall be \napplicable even while appointing an alternate director to an independent director in \nany of the Committees.', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 0]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\nDate: 22.05.2024 \n \nRef: IRDAI/F&I/CIR/MISC/82/5/2024 \n \nMaster Circular on Corporate Governance for Insurers, 2024 \n1. The Insurance Regulatory and Development Authority of India (Corporate Governance \nfor Insurers) Regulations, 2024  (“the Regula tions”) were notified on 21st March 2024.  \nThe Authority has outlined in general terms, governance responsibiliti es of the Board in \nthe management of insurers under the Regulations. In exercise of the powers conferred by \nSection 34 of the Insurance Act, 193 8, Section 14 of the IRDA Act, 1999 and Regulation \n12 of the Insurance Regulatory and Development Authority of India (Corporate \nGovernance for Insurers) Regulations, 2024 (“the Regulations”) the Authority hereby \nissues this master circular to provide vario us operational and procedural aspects, for \nadoption by all insurers. \n2. The title of this Master Circular shall be “ Master Circular on Corporate Governance for \nInsurers,2024”. \n3. This Master Circular shall be applicable to all insurers except foreign company eng aged \nin re-insurance business through a branch established in India.  \n4. This Master Circular becomes effective upon issuance. However, Insurers are given time \nup to 30 th June, 2024 to ensure compliance with its provisions. Further, where specific \ntimelines a re specified for certain compliances in this Master Circular, such timelines', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Corporate_Governance_for_Insurers_2024.pdf, Page: 17]\n[Document: Master Circular on Corporate Governance for Insurers 2024]\nInsurers. \n4.8 Ethics Committee (not mandatory) \nFunctions and Responsibilities of the Ethics Committee shall include: \n(A) Monitoring the compliance function and the insurance company’s \nrisk profile in respect of compliance with external laws and \nregulations and internal policies, including its code of ethics or \nconduct. \n(B) Receiving reports on the above and on proactive compliance \nactivities aimed at increasing the insurance company’s ability to \nmeet its legal and ethical obligations, on identified weaknesses, \nlapses, breaches or violations and the controls and other measures \nin place to help detect and address the same. \n(C) Supervising and monitoring matters reported using the insurer’s \nwhistle blowing or other  confidential mechanisms for employees \nand others to report ethical and compliance concerns or potential \nbreaches or violations.  \nAdvising th e board on the effect of the above on the insurer’s \nconduct of business and helping the board set the correct “tone at  \nthe top” by communicating, or supporting the communication, at \nall levels of the insurer of the importance of ethics and compliance.', '[Source: https://www.lexology.com/library/detail.aspx?g=8ea22c0a-b5c1-4437-92ec-e8a77d2c238e]\nIn May 2024, IRDAI notified a consolidated master circular for all matters relating to corporate governance in insurance companies. Together,', '[Source: https://irdai.gov.in/web/guest/document-detail?documentId=4916164]\nSecurities and Exchange Board of India (SEBI) · Reserve Bank of India (RBI) · Insolvency and Bankruptcy Board of India (IBBI) · Ministry Of Corporate Affairs (', '[Source: https://irdai.gov.in/circulars?p_p_id=com_irdai_document_media_IRDAIDocumentMediaPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_irdai_document_media_IRDAIDocumentMediaPortlet_filterDepartment=FNA&_com_irdai_document_media_IRDAIDocumentMediaPortlet_resetCur=false&_com_irdai_document_media_IRDAIDocumentMediaPortlet_delta=40]\nMaster Circular on Corporate Governance for Insurers, 2024, Master Circular on Corporate Governance for Insurers, 2024, 22-05-2024. pdf.', '[Source: https://irdai.gov.in/circulars?p_p_id=com_irdai_document_media_IRDAIDocumentMediaPortlet&p_p_lifecycle=0&p_p_state=normal&p_p_mode=view&_com_irdai_document_media_IRDAIDocumentMediaPortlet_cur=28&_com_irdai_document_media_IRDAIDocumentMediaPortlet_delta=20&_com_irdai_document_media_IRDAIDocumentMediaPortlet_orderByCol=dateid_String_sortable&_com_irdai_document_media_IRDAIDocumentMediaPortlet_orderByType=asc]\nMaster Circular on Corporate Governance for Insurers, 2024, Master Circular on Corporate Governance for Insurers, 2024, 22-05-2024. pdf.', '[Source: https://irdai.gov.in/documents/37343/365525/%E0%A4%AC%E0%A5%80%E0%A4%AE%E0%A4%BE%E0%A4%95%E0%A4%B0%E0%A5%8D%E0%A4%A4%E0%A4%BE%E0%A4%93%E0%A4%82+%E0%A4%95%E0%A5%87+%E0%A4%B2%E0%A4%BF%E0%A4%8F+%E0%A4%95%E0%A4%82%E0%A4%AA%E0%A4%A8%E0%A5%80+%E0%A4%85%E0%A4%AD%E0%A4%BF%E0%A4%B6%E0%A4%BE%E0%A4%B8%E0%A4%A8+%E0%A4%AA%E0%A4%B0+%E0%A4%AE%E0%A4%BE%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A4%B0+%E0%A4%AA%E0%A4%B0%E0%A4%BF%E0%A4%AA%E0%A4%A4%E0%A5%8D%E0%A4%B0,+2024+_+Master+Circular+on+Corporate+Governance+for+Insurers,+2024.pdf/ad741841-d705-96c8-cdf3-ba10eb89e592?version=1.0&t=1716382855018&download=true]\n(f). The Audit Committee shall have the oversight on the procedures and processes established to attend to issues relating to maintenance of', '[Source: https://www.veritaslegal.in/corporate-governance-for-insurers-a-new-robust-framework/]\nVeritas Legal\n\n# Corporate Governance for Insurers: A New Robust Framework\n\nAuthored by Shubhangi Pathak (Partner) and Aditi Mishra (Associate)\n\nIn furtherance of the Insurance Regulatory and Development Authority of India (Corporate Governance for Insurers) Regulations, 2024 (“the Regulations”) issued by the Insurance Regulatory and Development Authority of India (“IRDAI”), the Master Circular on Corporate Governance for Insurers, 2024 was notified on 22nd May 2024 (“Master Circular”), with an aim to provide various operational and procedural aspects for adoption by insurers. [...] The Master Circular repealed several circulars and guidelines including the Guidelines for Corporate Governance for Insurers in India, 2016. The intent of the Master Circular is to strengthen the capacity of key stakeholders responsible for an insurer’s governance – such as the board of directors (“Board”), senior management, and key management persons (“KMP”) to effectively and prudently manage the insurer’s business. The thrust of the Regulations and Master Circular is to further improve the corporate governance framework for Indian insurers.\n\nSome of the key aspects set out in the Regulations and the Master Circular are:\n\nBoard of Directors [...] Master Circular are another attempt towards this end where one of the key objectives is the protection of policyholders’ interests through more independent and well-structured corporate governance mechanisms being adopted and implemented by insurers.', '[Source: https://www.lexology.com/library/detail.aspx?g=ceb33ff1-fd25-44be-beec-f94614d2c093]\nIn 2024, we acted on 38% of all publicly disclosed mandates. ... This indicates a continued focus on board renewal by governance and nominating', '[Source: https://www.lexology.com/library/detail.aspx?g=487b817f-4bb0-4faf-b257-7f7619725783]\nThis is an indicative table of key dates (actual, expected and possible) during 2024. See sections below for further details.']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=744880;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 720.89s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 9 done (attempt 1).
   ⏳ Cooling down 10s (GPU cache cleared)...

📦 Evaluating batch 10 (Q10) [RAG/BOTH (all 4 metrics)]...

✨ You're running DeepEval's latest Faithfulness Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4), strict=False,
async_mode=False)...

✨ You're running DeepEval's latest Contextual Precision Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Contextual Recall Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

✨ You're running DeepEval's latest Answer Relevancy Metric! (using Qwen2.5-14B-Instruct-AWQ (local, T4),
strict=False, async_mode=False)...

Output()

======================================================================

Metrics Summary

  - ✅ Faithfulness (score: 0.875, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.88 because the actual output incorrectly presents the minimum percentage increase as 12.50% instead of 12.5% for the specified market-share band., error: None)
  - ✅ Contextual Precision (score: 1.0, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 1.00 because all the nodes in the retrieval contexts are relevant to the input, ensuring high precision without any irrelevant nodes., error: None)
  - ✅ Contextual Recall (score: 0.75, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.75 because the expected output accurately reflects the information provided in the 1st node of the retrieval context, including the minimum percentage increases for different market share bands and their applicability to general insurers, while noting that the instruction to check for updates is not explicitly stated in the retrieval context., error: None)
  - ✅ Answer Relevancy (score: 0.875, threshold: 0.5, strict: False, evaluation model: Qwen2.5-14B-Instruct-AWQ (local, T4), reason: The score is 0.88 because the response addresses the main points of the question regarding the percentage increases in motor third-party vehicle coverage but includes a redundant statement about the absence of new notifications, which does not add value and could be removed to improve relevance., error: None)

For test case:

  - input: Under the Master Circular on Rural, Social Sector and Motor Third Party Obligations 2025, what are the minimum percentage increases in motor third-party vehicle coverage for FY 2025-26 by market-share band, and are there any recent official IRDAI notifications updating these obligations?
  - actual output: **REGULATORY RULE:**
For the FY 2025‑26, the Master Circular on Rural, Social Sector and Motor Third‑Party Obligations specifies the minimum percentage increase in the number of Goods Carrying, Passenger Carrying Vehicles and Tractors (Miscellaneous segment) that each insurer must achieve, based on its Motor Third‑Party Insurance market‑share band:

| Market‑share band (of general insurer) | Minimum % increase for FY 2025‑26 |
|----------------------------------------|-----------------------------------|
| Up to 2 %                              | 12.50 %                           |
| 2 % – 5 %                               | 10.00 %                           |
| 5 % – 10 %                              | 7.50 %                            |
| More than 10 %                         | 5.00 %                            |

**CITATION:**
[Source: Master Circular on Rural Social Sector and Motor Third Party Obligations, Page 3]

---

**UPDATE STATUS:**
No additional or newer official IRDAI notifications that modify or supersede these motor‑third‑party coverage increase percentages are present in the supplied documents or web excerpts. The only references provided are to the original Master Circular and related announcements confirming its issuance, but none indicate subsequent amendments.

**CITATION:**
- No further IRDAI circulars or notifications updating these obligations are found in the provided web sources (e.g., IRDAI circular list, LinkedIn announcement).

**VERDICT:** INDETERMINATE (no evidence of recent updates).

**REASONING:** The table above directly answers the market‑share‑band percentages for FY 2025‑26 as stipulated in the Master Circular. A review of the available IRDAI web links and documents shows no later circular or amendment that alters these figures; therefore, we conclude that no recent official updates are available in the provided evidence.
  - expected output: The minimum percentage increase in number of Goods Carrying, Passenger Carrying Vehicles and Tractors for FY 2025-26 by market share band is: Up to 2% market share = 12.50% increase, 2%-5% = 10.00%, 5%-10% = 7.50%, More than 10% = 5.00%. These apply to all general insurers other than stand-alone health insurers, AIC and ECGC. For the web portion, the answer should check official IRDAI notification/circular pages for any updates or amendments to these obligations, and if none are found, state that no recent amendments could be confirmed from official sources.
  - context: None
  - retrieval context: ['[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 3]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nपृ� / Page 13 / 18 \n \n \nof all general insurers (other than stand -alone health insurers, AIC and \nECGC) shall be as under: \n \nFinancial \nyear \nMotor Third Party \nInsurance Market \nShare of general \ninsurer in the last \nfinancial year \nMinimum percentage increase in number of \nGoods Carrying, Passenger Carrying Vehicles \nand Tractors (Miscellaneous segment) over \nlast financial year separately for each category \n2025-26 2026-27 \nSecond \nand third \nYears \nUp to 2% 12.50% 13.75% \n2%-5% 10.00% 11% \n5%-10% 7.50% 8.25% \nMore than 10% 5.00% 5.50% \n  \nCHAPTER – III \n \nMethodology of arriving at the obligations with respect to Rural Sector \n \n4. What to Measure \n    \na) The respective Councils, in consultation with the insurers, as applicable: \n \ni. Shall identify the parameters such as market share or any other \nparameter to arrive at the minimum number of Gram Panchayats to be \nallotted to each insurer. \nii. Shall, based on such parameters as applicable to each insurer, \ndetermine the minimum number of the Gram Panchayats to be allotted \ninsurer-wise \niii. Shall inform the minimum number of gram panchayats to the life insurers, \ngeneral insurer -1 and general insurer – 2, as applicable: \n \na. by at least 45 days before the end of immediate preceding Financial \nYear (FY). \n \nb) On receipt of the minimum number of Gram Panchayats to be covered, each', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 3]\nपृ� / Page 13 / 18 \n \n \nof all general insurers (other than stand -alone health insurers, AIC and \nECGC) shall be as under: \n \nFinancial \nyear \nMotor Third Party \nInsurance Market \nShare of general \ninsurer in the last \nfinancial year \nMinimum percentage increase in number of \nGoods Carrying, Passenger Carrying Vehicles \nand Tractors (Miscellaneous segment) over \nlast financial year separately for each category \n2025-26 2026-27 \nSecond \nand third \nYears \nUp to 2% 12.50% 13.75% \n2%-5% 10.00% 11% \n5%-10% 7.50% 8.25% \nMore than 10% 5.00% 5.50% \n  \nCHAPTER – III \n \nMethodology of arriving at the obligations with respect to Rural Sector \n \n4. What to Measure \n    \na) The respective Councils, in consultation with the insurers, as applicable: \n \ni. Shall identify the parameters such as market share or any other \nparameter to arrive at the minimum number of Gram Panchayats to be \nallotted to each insurer. \nii. Shall, based on such parameters as applicable to each insurer, \ndetermine the minimum number of the Gram Panchayats to be allotted \ninsurer-wise \niii. Shall inform the minimum number of gram panchayats to the life insurers, \ngeneral insurer -1 and general insurer – 2, as applicable: \n \na. by at least 45 days before the end of immediate preceding Financial \nYear (FY). \n \nb) On receipt of the minimum number of Gram Panchayats to be covered, each', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 2]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nthe year \n \n(B) Obligations with respect to Social Sector: \n \na) All Insurers –  In accordance with Regulation 7 (C) of IRDAI (Rural, Social \nSector and Motor Third Party Obligations) Regulations, 2024, the Social \nSector obligations for the second and third year  in respect of all Insurers \n(Life, General and Standalone Health, excluding AIC and ECGC) shall be as \nunder: \n \nFinancial year Minimum percentage of lives to be covered under \nsocial sector as a proportion of total lives covered \n2025-26 10% \n2026-27 12% \n \n(C) Obligations with respect to Motor Third Party Business: \n \na) All General Insurers (other than stand- alone health insurers, AIC and \nECGC) –  In accordance with Regulation 7 (C) of IRDAI (Rural, Social Sector \nand Motor Third Party Obligations) Regulations, 2024, the obligations with \nrespect to motor third party business for the second and third year in respect', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 1]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nपृ� / Page 11 / 18 \n \n \n \ni. Every life insurer shall cover minimum specified percentage of lives under \nindividual and/ or group insurance policies in allocated Gram Panchayats \nand all insurers collectively shall cover specified minimum number of \nGram panchayats. \nii. The Rural Sector obligation for second and third year, in accordance with \nRegulation 7 (C) of IRDAI (Rural, Social Sector and Motor Third Party \nObligations) Regulations, 2024, shall be as under: -.  \n \nFinancial year Minimum number of Gram \nPanchayats to be allotted \nto the insurers by the \nCouncil \nMinimum percentage of lives \nto be covered in a Gram \npanchayat by the insurers \n2025-26 25000 15% \n2026-27 50000 \n(i) 25% for the GPs allocated \nfor the previous years and \n(ii) 10% for newly added \nGram Panchayats during the \nyear \n \nb) General Insurance (General Insurers other than stand -alone health \ninsurer(SAHI), Agriculture Insurance Co. Ltd (AIC) and ECGC) – \n \ni. Every General Insurer-1 shall cover minimum specified percentage of a) \ndwellings and shops under Fire insurance; and b) vehicles under motor \ninsurance in allocated Gram Panchayats and all insurers collectively shall \ncover specified minimum number of gram panchayats. \nii. The Rural Obligation for second and third year in accordance with \nRegulation 7 ( C) of IRDAI (Rural, Social Sector and Motor Third Party', '[Source: /kaggle/input/datasets/ashishmm10/irdaidataset/Master_Circular_on_Rural_Social_Sector_and_Motor_Third_Party_Obligations.pdf, Page: 1]\n[Document: Master Circular on Rural Social Sector and Motor Third Party Obligations]\nii. The Rural Obligation for second and third year in accordance with \nRegulation 7 ( C) of IRDAI (Rural, Social Sector and Motor Third Party \nObligations) Regulations, 2024 shall be as under:  \n \nFinancial year Minimum number of \nGram Panchayats to \nbe allotted to the \ninsurers by the \nCouncil \nMinimum percentage \nof dwellings and shops \nto be covered in a  \nGram panchayat (GP) \nMinimum percentage of \nvehicles to be covered \nunder motor insurance \nin a Gram panchayat \n(GP) \n2025-26 25000 15% 15% \n2026-27 50000 \n(i) 25% for the GPs \nallocated for the \nprevious years and \n(i) 25% for the GPs \nallocated for the \nprevious years and \n(ii) 10% for newly \nadded Gram \nPanchayats during the \nyear \n(ii) 10% for newly \nadded Gram \nPanchayats during the \nyear', "[Source: https://www.teamleaseregtech.com/updates/article/45000/master-circular-on-rural-social-sector-and-motor-third-party-obligatio]\nThis increase varies from 5% to 12.5% for FY 2025-26 (and 5.5% to 13.75% for FY 2026-27), depending on the insurer's market share in the", '[Source: https://irdai.gov.in/circulars]\n... Financial Year 2025-26, परिपत्र / CIRCULAR, 25-03-2026. pdf ... Master Circular on Rural, Social Sector and Motor Third Party Obligations', '[Source: https://www.linkedin.com/posts/anurag-shah-06607929_insuranceforall-irdai-ruralpush-activity-7354544389060280320-hBHN]\nAgree & Join LinkedIn\n\nBy clicking Continue to join or sign in, you agree to LinkedIn’s User Agreement, Privacy Policy, and Cookie Policy.\n\n# IRDAI issues Master Circular on Rural, Social & Motor TP obligations for 2025-26 & 2026-27\n\nView profile for Anurag Shah\n\nTimes Network•9K followers\n\nET NOW News Break Confirmed: IRDAI issues Master Circular on Rural, Social & Motor TP obligations for 2025-26 & 2026-27. Insurers must cover lives/vehicles in 25,000 Gram Panchayats in FY26 (15% obligation), rising to 50,000 in FY27 with 25% continuity and 10% new additions. Social sector targets fixed at 10% (FY26) and 12% (FY27). Motor TP obligation rates unchanged for FY26, hiked for FY27.\n#InsuranceForAll #IRDAI #RuralPush #SocialSecurity #MotorTP #FinancialInclusion #BharatFirst [...] #InsuranceMantra #ETNowExclusive #NewIndiaAssurance #GirijaSubramanian #InsuranceForAll #GSTImpact #HealthInsurance #InsuranceAwareness #PSUInsurers #AgentCommissions [...] #InsuranceMantra #ETNowExclusive #NewIndiaAssurance #GirijaSubramanian #InsuranceForAll #GSTImpact #HealthInsurance #InsuranceAwareness #PSUInsurers #AgentCommissions', '[Source: https://irdai.gov.in/documents/37343/365525/%E0%A4%97%E0%A5%8D%E0%A4%B0%E0%A4%BE%E0%A4%AE%E0%A5%80%E0%A4%A3%2C+%E0%A4%B8%E0%A4%BE%E0%A4%AE%E0%A4%BE%E0%A4%9C%E0%A4%BF%E0%A4%95+%E0%A4%95%E0%A5%8D%E0%A4%B7%E0%A5%87%E0%A4%A4%E0%A5%8D%E0%A4%B0+%E0%A4%94%E0%A4%B0+%E0%A4%AE%E0%A5%8B%E0%A4%9F%E0%A4%B0+%E0%A4%85%E0%A4%A8%E0%A5%8D%E0%A4%AF+%E0%A4%AA%E0%A4%95%E0%A5%8D%E0%A4%B7+%E0%A4%A6%E0%A4%BE%E0%A4%AF%E0%A4%BF%E0%A4%A4%E0%A5%8D%E0%A4%B5%E0%A5%8B%E0%A4%82+%E0%A4%B8%E0%A4%82%E0%A4%AC%E0%A4%82%E0%A4%A7%E0%A5%80+%E0%A4%AE%E0%A4%BE%E0%A4%B8%E0%A5%8D%E0%A4%9F%E0%A4%B0+%E0%A4%AA%E0%A4%B0%E0%A4%BF%E0%A4%AA%E0%A4%A4%E0%A5%8D%E0%A4%B0+_+Master+Circular+on+Rural%2C+Social+Sector+and+Motor+Third+Party+Obligations.pdf/22343683-1b1b-8b6b-55f7-f80317a4cad8?version=1.0&t=1753450439575&download=true]\nThe Master Circular on Rural, Social Sector and Motor Third. Party Obligations, 2025 shall be applicable for the FY 2025-26 and FY. 2026-27. 2.', '[Source: https://irdai.gov.in/document-detail?documentId=4858052]\nग्रामीण, सामाजिक क्षेत्र और मोटर तृतीय पक्ष दायित्व पर मास्टर परिपत्र _ Master Circular on RUSO and MTP Obligations.pdf · Download · file icon. ग्रामीण, सामाजिक क्षेत्र और मोटर तृतीय पक्ष दायित्व पर']

======================================================================

Overall Metric Pass Rates

Faithfulness: 100.00% pass rate
Contextual Precision: 100.00% pass rate
Contextual Recall: 100.00% pass rate
Answer Relevancy: 100.00% pass rate

======================================================================

⚠ WARNING: No hyperparameters logged.
» ]8;id=332392;https://deepeval.com/docs/evaluation-prompts\Log hyperparameters]8;;\ to attribute prompts and models to your test runs.

================================================================================

✓ Evaluation completed 🎉! (time taken: 1057.98s | token cost: None)
» Test Results (1 total tests):
   » Pass Rate: 100.0% | Passed: 1 | Failed: 0

 ================================================================================

» Want to share evals with your team, or a place for your test cases to live? ❤️ 🏡
  » Run 'deepeval view' to analyze and save testing results on Confident AI.

   ✅ Batch 10 done (attempt 1).

✅ Full DeepEval evaluation complete!
   📊 Collected results for 10 out of 10 test cases.

## Parse results into a DataFrame:

In [11]:
# ═══════════════════════════════════════════════════════════════════
# Results export — updated for route-aware evaluation
# ═══════════════════════════════════════════════════════════════════
rows = []

for idx, (r, tc_result) in enumerate(zip(results, all_results_eval)):
    row = {
        "q_id": r["q_id"],
        "expected_route": r["expected_route"],
        "actual_route": r["actual_route"],
        "fallback_used": r["fallback_used"],
        "fallback_reason": r["fallback_reason"],
        "router_confidence": r["router_confidence"],
        "question": r["question"],
    }

    for metric_result in tc_result.metrics_data:
        col = metric_result.name.lower().replace(" ", "_")
        row[col] = metric_result.score if metric_result.success is not None else float("nan")
        row[f"{col}_reason"] = metric_result.reason

    rows.append(row)

scores_df = pd.DataFrame(rows)

# These columns may not exist for WEB-only questions — handle gracefully
metric_cols = ["faithfulness", "contextual_precision", "contextual_recall", "answer_relevancy"]
available_cols = [c for c in metric_cols if c in scores_df.columns]

print("\n📊 Per-Question Scores:")
display(scores_df[["q_id", "expected_route", "actual_route", "fallback_used"] + available_cols])

print("\n🏆 Overall Mean Scores (all questions):")
print(scores_df[available_cols].mean(skipna=True).round(3))

# Also show means split by route type
print("\n📈 Scores by Route Type:")
for route in ["RAG", "WEB", "BOTH"]:
    subset = scores_df[scores_df["expected_route"] == route]
    if len(subset) > 0:
        print(f"\n  {route} ({len(subset)} questions):")
        print(f"  {subset[available_cols].mean(skipna=True).round(3).to_dict()}")

scores_df.to_excel('/kaggle/working/deepeval_scores_v3.xlsx', index=False)
print("\n✅ File saved to /kaggle/working/deepeval_scores_v3.xlsx")

📊 Per-Question Scores:

,q_id,expected_route,actual_route,fallback_used,faithfulness,contextual_precision,contextual_recall,answer_relevancy
0,Q01,RAG,RAG,False,1.000000,1.00,1.000000,1.000000
1,Q02,RAG,RAG,False,0.714286,1.00,1.000000,1.000000
2,Q03,RAG,RAG,False,1.000000,1.00,1.000000,1.000000
3,Q04,RAG,RAG,False,1.000000,0.75,1.000000,1.000000
4,Q05,WEB,WEB,False,0.800000,NaN,NaN,1.000000
5,Q06,WEB,WEB,False,1.000000,NaN,NaN,1.000000
6,Q07,WEB,WEB,False,1.000000,NaN,NaN,0.333333
7,Q08,BOTH,BOTH,False,0.600000,1.00,0.666667,1.000000
8,Q09,BOTH,BOTH,False,0.750000,1.00,0.500000,0.500000
9,Q10,BOTH,BOTH,False,0.875000,1.00,0.750000,0.875000

🏆 Overall Mean Scores (all questions):
faithfulness            0.874
contextual_precision    0.964
contextual_recall       0.845
answer_relevancy        0.871
dtype: float64

📈 Scores by Route Type:

  RAG (4 questions):
  {'faithfulness': 0.929, 'contextual_precision': 0.938, 'contextual_recall': 1.0, 'answer_relevancy': 1.0}

  WEB (3 questions):
  {'faithfulness': 0.933, 'contextual_precision': nan, 'contextual_recall': nan, 'answer_relevancy': 0.778}

  BOTH (3 questions):
  {'faithfulness': 0.742, 'contextual_precision': 1.0, 'contextual_recall': 0.639, 'answer_relevancy': 0.792}

✅ File saved to /kaggle/working/deepeval_scores_v3.xlsx